-- Seed file for Paris activities
-- Generated from provided data
-- price_range: gratuit | euro (<20€) | euro2 (20-50€) | euro3 (>50€)

-- JARDINS (Gardens) - Tous gratuits
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website, already_done) VALUES
('Jardin Montsouris', 'Magnifique parc à l''anglaise de 15 hectares avec pelouses vallonnées, lac et sculptures. Idéal pour pique-niques et promenades.', 'jardin', 'https://parisauthority.com/ckeditor_assets/pictures/501/medium_parc-montsouris-paris.jpg', 'Paris', '14', 'gratuit', NULL, ARRAY['nature', 'famille', 'pique-nique', 'lac'], 'https://www.paris.fr/lieux/parc-montsouris-1810', false),
('Jardin des Tuileries', 'Jardin historique créé au XVIe siècle, reliant le Louvre à la place de la Concorde. Sculptures, bassins et chaises emblématiques.', 'jardin', 'https://i.familiscope.fr/1400x787/smart/2022/04/25/jardin-des-tuileries-paris-musee-du-louvre.jpg', 'Paris', '1', 'gratuit', NULL, ARRAY['histoire', 'sculptures', 'centre-ville', 'romantique'], 'https://www.louvre.fr/en/explore/the-palace/the-tuileries-garden', true),
('Jardin du Palais Royal', 'Écrin de verdure entouré d''arcades élégantes. Un havre de paix au cœur de Paris avec les colonnes de Buren.', 'jardin', 'https://paris1900.lartnouveau.com/paris01/palais_royal/jardin/1jar_pr56.jpg', 'Paris', '1', 'gratuit', NULL, ARRAY['histoire', 'architecture', 'calme', 'centre-ville'], 'https://www.domaine-palais-royal.fr/', false),
('Jardins du Trocadéro', 'Jardins offrant une vue imprenable sur la Tour Eiffel, avec fontaines spectaculaires et architecture Art Déco.', 'jardin', 'https://c8.alamy.com/compfr/2cc6g83/paris-france-2-aout-2013-vue-aerienne-de-nombreux-touristes-visitant-le-jardin-du-trocadero-jardins-du-trocadero-depuis-la-tour-eiffel-a-paris-france-2cc6g83.jpg', 'Paris', '16', 'gratuit', NULL, ARRAY['tour-eiffel', 'fontaines', 'vue', 'photo'], 'https://www.paris.fr/lieux/jardins-du-trocadero-1783', true),
('Parc Floral de Paris', 'Le plus grand jardin botanique de Paris avec collections de plantes, aires de jeux et concerts en été.', 'jardin', 'https://cdn.paris.fr/paris/2019/09/12/huge-5c5f642f666ab66fd807e6f416a48281.jpg', 'Paris', '12', 'gratuit', NULL, ARRAY['botanique', 'fleurs', 'famille', 'concerts'], 'https://www.paris.fr/lieux/parc-floral-de-paris-1808', false),
('Parc Monceau', 'Parc romantique du XVIIIe siècle avec fausses ruines, colonnade corinthienne et atmosphère bucolique.', 'jardin', 'https://www.unjourdeplusaparis.com/wp-content/uploads/2022/01/colonnade-naumachie-monceau.jpg', 'Paris', '8', 'gratuit', NULL, ARRAY['romantique', 'histoire', 'ruines', 'élégant'], 'https://www.paris.fr/lieux/parc-monceau-1804', false),
('Parc de Bercy', 'Ancien site viticole transformé en parc contemporain avec jardins thématiques, passerelle et vignes.', 'jardin', 'https://cdn.paris.fr/eqpts-prod/2023/07/12/f26d718c6a30e49ac0562ba5debc4ddc.jpg', 'Paris', '12', 'gratuit', NULL, ARRAY['moderne', 'vignes', 'famille', 'sport'], 'https://www.paris.fr/lieux/parc-de-bercy-1792', false),
('Parc de la Villette', 'Le plus grand parc de Paris avec Cité des Sciences, Géode, Philharmonie et nombreuses activités culturelles.', 'jardin', 'https://www.lavillette.com/wp-content/uploads/2024/01/65-VIL_0080134-1-1024x727.jpg', 'Paris', '19', 'gratuit', NULL, ARRAY['culture', 'sciences', 'concerts', 'famille'], 'https://lavillette.com/', false),
('Parc Clichy-Batignolles Martin Luther King', 'Parc écologique moderne avec jardins partagés, skatepark et architecture contemporaine.', 'jardin', 'https://cdn.paris.fr/eqpts-prod/2022/05/10/large-801b0cec75e2127a3da91742b1303556.jpg', 'Paris', '17', 'gratuit', NULL, ARRAY['écologique', 'moderne', 'skatepark', 'famille'], 'https://www.paris.fr/lieux/parc-clichy-batignolles-martin-luther-king-1798', false),
('Parc de l''Île Saint-Germain', 'Île verdoyante sur la Seine avec la Tour aux Figures de Jean Dubuffet et espaces de détente.', 'jardin', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/49/56/44/vue-aerienne-du-parc.jpg?w=700&h=-1&s=1', 'Issy-les-Moulineaux', NULL, 'gratuit', NULL, ARRAY['île', 'sculpture', 'nature', 'tranquille'], 'https://www.issy.com/nature-proprete/nature-en-ville/ile-saint-germain', false),
('Domaine National de Saint-Cloud', 'Immense domaine royal de 460 hectares avec jardins à la française, cascades et vue panoramique sur Paris.', 'jardin', 'https://www.hauts-de-seine.fr/fileadmin/_processed_/3/f/csm_saintcloud1_1005999dec.jpg', 'Saint-Cloud', NULL, 'gratuit', NULL, ARRAY['domaine-royal', 'panorama', 'cascades', 'histoire'], 'http://www.domaine-saint-cloud.fr/', false),
('Parc Edmond de Rothschild', 'Parc paysager de style anglais avec étang, cascades et arbres centenaires à Boulogne-Billancourt.', 'jardin', 'https://exploreparis.com/14594/parc-rothschild-solidarite-vegetale.jpg', 'Boulogne-Billancourt', NULL, 'gratuit', NULL, ARRAY['anglais', 'étang', 'arbres', 'calme'], 'https://www.boulognebillancourt.com/', false),
('Jardin du Ruisseau', 'Jardin associatif caché sur une ancienne voie ferrée de la Petite Ceinture. Un secret bien gardé du 18e.', 'jardin', 'https://lesjardinsduruisseau.fr/wp-content/uploads/2017/05/DSC_0453-500x300.jpg', 'Paris', '18', 'gratuit', NULL, ARRAY['associatif', 'secret', 'petite-ceinture', 'alternatif'], 'https://lejardinduruisseau.org/', false),
('Les Plus Beaux Jardins de France', 'Espace vert élégant près des Champs-Élysées célébrant l''art des jardins français.', 'jardin', 'https://images.ctfassets.net/43cg184ejz07/b2JY1cTjR5jVR2U6RWu0m/83c48678380d15d3cde6103e824613f6/RBD090718-722-HDR_03.jpg?fm=jpg&w=1024&h=576&fit=fill', 'Paris', '8', 'gratuit', NULL, ARRAY['élégant', 'champs-élysées', 'français'], 'https://www.paris.fr/', false),
('Parc de la Vallée aux Loups', 'Arboretum romantique de 13 hectares avec collections botaniques exceptionnelles et maison de Chateaubriand.', 'jardin', 'https://cdn.paris.fr/paris/2023/04/04/huge-13b41bfb18ff3f286d4d0b9145250340.jpeg', 'Châtenay-Malabry', NULL, 'gratuit', NULL, ARRAY['arboretum', 'romantique', 'littérature', 'botanique'], 'https://vallee-aux-loups.hauts-de-seine.fr/', false),
('Coulée Verte René-Dumont', 'Promenade plantée de 4,7 km sur une ancienne voie ferrée, précurseur de la High Line de New York.', 'jardin', 'https://www.baladesauxjardins.fr/wp-content/uploads/2018/04/Coulée-verte-René-Dumont-canal-à-la-persane.jpg', 'Paris', '12', 'gratuit', NULL, ARRAY['promenade', 'voie-ferrée', 'original', 'marche'], 'https://www.paris.fr/lieux/coulee-verte-rene-dumont-ex-promenade-plantee-1784', false),
('Parc de Belleville', 'Parc en terrasses offrant l''un des plus beaux panoramas sur Paris, avec vignes et cascades.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/P1010851_Paris_XX_Parc_de_Belleville_reductwk.JPG/1200px-P1010851_Paris_XX_Parc_de_Belleville_reductwk.JPG', 'Paris', '20', 'gratuit', NULL, ARRAY['panorama', 'terrasses', 'vignes', 'vue'], 'https://www.paris.fr/lieux/parc-de-belleville-1791', false),
('Parc des Buttes-Chaumont', 'Parc romantique du XIXe siècle avec lac, grottes, cascades et temple de la Sibylle perché sur un rocher.', 'jardin', 'https://cloudfront-eu-central-1.images.arcpublishing.com/leparisien/X63ABGT676P6G7MSM5LKRBHWCI.jpg', 'Paris', '19', 'gratuit', NULL, ARRAY['romantique', 'lac', 'grottes', 'temple'], 'https://www.paris.fr/lieux/parc-des-buttes-chaumont-1757', false),
('Jardin des Plantes', 'Plus ancien jardin botanique de France avec serres tropicales, ménagerie et Muséum d''Histoire naturelle.', 'jardin', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/d2/88/a1/jardin-des-plantes.jpg?w=900&h=500&s=1', 'Paris', '5', 'gratuit', NULL, ARRAY['botanique', 'serres', 'zoo', 'sciences'], 'https://www.jardindesplantesdeparis.fr/', false),
('Jardin du Luxembourg', 'Jardin emblématique de Paris avec son palais, bassins, statues et atmosphère unique du Quartier Latin.', 'jardin', 'https://jardin.senat.fr/fileadmin/_processed_/b/b/csm_aqueduc1_39288b39d4.webp', 'Paris', '6', 'gratuit', NULL, ARRAY['emblématique', 'palais', 'quartier-latin', 'romantique'], 'https://www.senat.fr/visite/jardin/', false),
('Jardin Atlantique', 'Jardin suspendu au-dessus des voies de la gare Montparnasse, oasis de verdure inattendue.', 'jardin', 'https://paris1900.lartnouveau.com/paris15/jardin_atlantique/1jard_atlan55.jpg', 'Gare Montparnasse', '15', 'gratuit', '1h30', ARRAY['suspendu', 'moderne', 'insolite', 'gare'], 'https://www.paris.fr/lieux/jardin-atlantique-1782', true);

-- PARCS D'ATTRACTIONS
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website, already_done) VALUES
('Jardin d''Acclimatation', 'Parc d''attractions familial historique au cœur du Bois de Boulogne avec manèges, ferme et jardins.', 'parc', 'https://paris.kidiklik.fr/sites/default/files/styles/crop_image/public/2024-04/Jardin%20Acclimatation%20825x426.png?itok=ZI5YmjO8', 'Paris', '16', 'euro2', 'journée', ARRAY['attractions', 'famille', 'manèges', 'animaux'], 'https://www.jardindacclimatation.fr/', false),
('Disneyland Paris - 1 jour', 'Le célèbre parc à thèmes Disney avec deux parcs, attractions magiques et spectacles féeriques.', 'parc', 'https://news.disneylandparis.com//app/uploads/2023/10/D100.jpg', 'Marne-la-Vallée', NULL, 'euro3', '1 jour', ARRAY['disney', 'attractions', 'magie', 'famille'], 'https://www.disneylandparis.com/', false),
('Disneyland Paris - 2 jours', 'Profitez de deux jours pour explorer les deux parcs Disney et vivre la magie sans vous presser.', 'parc', 'https://news.disneylandparis.com//app/uploads/2023/10/D100.jpg', 'Marne-la-Vallée', NULL, 'euro3', '2 jours', ARRAY['disney', 'attractions', 'magie', 'famille'], 'https://www.disneylandparis.com/', false),
('Aquaboulevard', 'Le plus grand parc aquatique urbain d''Europe avec piscines à vagues, toboggans et espaces détente.', 'parc', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/30/21/2b/parc.jpg?w=1200&h=-1&s=1', 'Paris', '15', 'euro2', 'journée', ARRAY['aquatique', 'piscine', 'toboggans', 'famille'], 'https://www.aquaboulevard.fr/', false);

-- CHÂTEAUX
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website, already_done) VALUES
('Château de Vincennes', 'Imposante forteresse médiévale avec le plus haut donjon de France et la Sainte-Chapelle.', 'chateau', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXUH8AQgjKrNNmci6xmGsZ4jnAGQr4fqsi_A&s', 'Vincennes', NULL, 'euro', 'journée', ARRAY['médiéval', 'donjon', 'histoire', 'forteresse'], 'http://www.chateau-vincennes.fr/', false),
('Château de Versailles', 'L''emblématique résidence royale avec ses jardins à la française, galerie des Glaces et Trianons.', 'chateau', 'https://www.parisselectbook.com/wp-content/uploads/2024/06/Paris-Select-18.jpg', 'Versailles', NULL, 'euro2', 'journée', ARRAY['royal', 'jardins', 'louis-xiv', 'unesco'], 'https://www.chateauversailles.fr/', false),
-- ('Château de Chantilly', 'Joyau Renaissance abritant le musée Condé, deuxième collection de peintures anciennes de France.', 'chateau', 'https://www.saintclair.com/app/uploads/2023/09/chantilly-rares-sont-les-chateaux-ou-l-on-peut-ressentir-l-histoire-d-aussi-pres-photo-dr-1605002910.jpg', 'Chantilly', NULL, 'euro', 'journée', ARRAY['renaissance', 'musée', 'jardins', 'équitation'], 'https://www.chateaudechantilly.fr/', false),
-- ('Château de Fontainebleau', 'Résidence royale de 800 ans d''histoire, de François Ier à Napoléon III, avec forêt majestueuse.', 'chateau', 'https://cdn.essentiels.bnf.fr/media/images/cache/crop/rc/koMsergQ/uploads/media/image/20201204160522000000_pas_1192.jpg', 'Fontainebleau', NULL, 'euro', 'journée', ARRAY['royal', 'napoléon', 'forêt', 'histoire'], 'https://www.chateaudefontainebleau.fr/', false),
-- ('Château de Rambouillet', 'Ancienne résidence présidentielle avec parc de 100 hectares, laiterie de la Reine et chaumière.', 'chateau', 'https://parisjetaime.com/data/layout_grouping/product_index_slideshow/70678_chteau-2.1000w.JPG?ver=1720689089', 'Rambouillet', NULL, 'euro', 'journée', ARRAY['présidentiel', 'parc', 'histoire', 'nature'], 'http://www.chateau-rambouillet.fr/', false),
('Château de Champs-sur-Marne', 'Élégant château du XVIIIe siècle avec intérieurs raffinés et jardins à la française remarquables.', 'chateau', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFd166N5xH34bCVXBoFEZ_MCRR5Wk6jjZUdw&s', 'Champs-sur-Marne', NULL, 'euro', 'journée', ARRAY['xviiie', 'jardins', 'élégant', 'cinéma'], 'http://www.chateau-champs-sur-marne.fr/', false),
-- ('Château de Vaux-le-Vicomte', 'Chef-d''œuvre de Le Vau, Le Brun et Le Nôtre, modèle de Versailles. Soirées aux chandelles l''été.', 'chateau', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQL5jDlnL7TvoojBQsLnNTBg2nZS0SESFJ-A&s', 'Maincy', NULL, 'euro2', 'journée', ARRAY['baroque', 'jardins', 'chandelles', 'fouquet'], 'https://vaux-le-vicomte.com/', false),
('Château de Maisons-Laffitte', 'Chef-d''œuvre de l''architecture classique française par François Mansart, décors d''origine préservés.', 'chateau', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHUKZsre1yfRWknAw7jE08YyGeKtD1wcT9eg&s', 'Maisons-Laffitte', NULL, 'euro', 'journée', ARRAY['classique', 'mansart', 'architecture', 'chevaux'], 'http://www.chateau-maisons.fr/', false),
-- ('Château de Breteuil', 'Château familial avec mise en scène des contes de Perrault et magnifique jardin labellisé.', 'chateau', 'https://www.breteuil.fr/wp-content/uploads/2021/04/vue-aerienne-breteuil.png', 'Choisel', NULL, 'euro', 'journée', ARRAY['famille', 'contes', 'perrault', 'jardins'], 'https://www.breteuil.fr/', false);

-- MUSÉES
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website, already_done) VALUES
('Musée de l''Illusion', 'Expériences visuelles et sensorielles étonnantes, illusions d''optique et installations interactives.', 'musee', 'https://storage.canalblog.com/74/59/1637944/125868037_o.jpg', 'Paris', '1', 'euro', '1h30', ARRAY['interactif', 'illusions', 'photos', 'famille'], 'https://museedelillusion.fr/', false),
('Fondation Louis Vuitton', 'Bâtiment iconique de Frank Gehry abritant art moderne et contemporain avec vue panoramique.', 'musee', 'https://www.franceguide.info/fr/wp-content/uploads/sites/20/paris-fondation-louis-vuitton.jpg', 'Paris', '16', 'euro', '2h', ARRAY['architecture', 'art-moderne', 'gehry', 'vue'], 'https://www.fondationlouisvuitton.fr/', false),
('Musée du Louvre', 'Le plus grand musée d''art au monde avec la Joconde, la Vénus de Milo et 35 000 œuvres exposées.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/1280px-Louvre_Museum_Wikimedia_Commons.jpg', 'Paris', '1', 'euro2', '2h30', ARRAY['art', 'joconde', 'incontournable', 'histoire'], 'https://www.louvre.fr/', false),
('Musée d''Orsay', 'Ancienne gare reconvertie en musée impressionniste avec Monet, Van Gogh, Renoir et plus encore.', 'musee', 'https://asset-prod.france.fr/France_Seine_Paris_musee_d_Orsay_42258_Patrice_Schmidt_de06a75b85.jpg', 'Paris', '7', 'euro', '1h30', ARRAY['impressionnisme', 'gare', 'art', 'xixe'], 'https://www.musee-orsay.fr/', false),
('Musée de l''Orangerie', 'Écrin des Nymphéas de Monet et collection Walter-Guillaume d''art impressionniste et moderne.', 'musee', 'https://cdn.mediatheque.epmoo.fr/link/3c9igq/wdb19r8krqu6jj4.jpg', 'Paris', '1', 'euro', '1h30', ARRAY['monet', 'nymphéas', 'impressionnisme', 'tuileries'], 'https://www.musee-orangerie.fr/', false),
('Grand Palais', 'Monument emblématique de Paris avec sa verrière spectaculaire, accueillant grandes expositions.', 'musee', 'https://www.chatillonarchitectes.com/wp-content/uploads/2025/07/04-Le-Grand-Palais-Chatillon-Architectes-Paris-©-Charly-Broyez_JOUR2_BRUT_NE-PAS-DIFFUSER-1-copie-1.jpg', 'Paris', '8', 'euro', '1h30', ARRAY['expositions', 'verrière', 'champs-élysées', 'architecture'], 'https://www.grandpalais.fr/', false),
('Petit Palais', 'Musée des Beaux-Arts de la Ville de Paris avec collections permanentes gratuites et jardin intérieur.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/7/71/Petit-Palais-Paris-02-2018.jpg', 'Paris', '8', 'gratuit', '1h', ARRAY['gratuit', 'beaux-arts', 'jardin', 'classique'], 'https://www.petitpalais.paris.fr/', false),
('Musée Grévin', 'Célèbre musée de cire avec plus de 200 personnalités en figures plus vraies que nature.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Mus%C3%A9e_Gr%C3%A9vin%2C_Paris_30_July_2016.jpg/330px-Mus%C3%A9e_Gr%C3%A9vin%2C_Paris_30_July_2016.jpg', 'Boulevard Montmartre', '9', 'euro2', '1h30', ARRAY['cire', 'célébrités', 'photos', 'famille'], 'https://www.grevin-paris.com/', true),
('Musée des Arts et Métiers', 'Conservatoire des techniques et de l''innovation avec pendule de Foucault et avion de Blériot.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/5/59/Mus%C3%A9e_des_Arts_et_M%C3%A9tiers_337.jpg', 'Paris', '3', 'euro', '3h', ARRAY['sciences', 'techniques', 'inventions', 'foucault'], 'https://www.arts-et-metiers.net/', false),
('Musée de la Chasse et de la Nature', 'Collection unique sur les rapports homme-animal dans un hôtel particulier du Marais.', 'musee', 'https://www.familinparis.fr/wp-content/uploads/photos-familinparis-2021/mus%C3%A9e/musee-de-la-chasse/trophee-musee-de-la-chasse-marais-1500x1125-1.jpg', 'Paris', '3', 'euro', '1h30', ARRAY['nature', 'animaux', 'marais', 'original'], 'https://www.chassenature.org/', false),
('Musée Carnavalet', 'L''histoire de Paris des origines à nos jours dans deux hôtels particuliers du Marais.', 'musee', 'https://www.carnavalet.paris.fr/sites/default/files/styles/576x/public/2021-05/wec2104_chatillon_carnavalet_s1090294.jpg?itok=UfEZa28f', 'Paris', '3', 'gratuit', '2h', ARRAY['paris', 'histoire', 'marais', 'gratuit'], 'https://www.carnavalet.paris.fr/', false),
('Musée Picasso', 'La plus grande collection mondiale d''œuvres de Picasso dans l''Hôtel Salé au cœur du Marais.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/H%C3%B4tel_Sal%C3%A9.JPG/330px-H%C3%B4tel_Sal%C3%A9.JPG', 'Paris', '3', 'euro', '2h', ARRAY['picasso', 'art-moderne', 'marais', 'sculpture'], 'https://www.museepicassoparis.fr/', false),
('Archives Nationales', 'Trésors de l''histoire de France dans le cadre somptueux de l''Hôtel de Soubise et Rohan.', 'musee', 'https://s3.fr-par.scw.cloud/an-p0-bucket/an-public/styles/ds_cartes_image_illustrative/public/files/D%C3%A9couvrir/Lieux%20dexception/visuels%20Soubise%202025/Soubise_cour.jpg?VersionId=1754485564532613&h=ebb3b0b2&itok=1SgZEApO', 'Paris', '3', 'gratuit', '1h30', ARRAY['histoire', 'archives', 'gratuit', 'documents'], 'https://www.archives-nationales.culture.gouv.fr/', false),
('Musée de la Magie', 'Univers fascinant de la prestidigitation avec spectacles de magie et collection d''automates.', 'musee', 'https://www.franceinfo.fr/pictures/NiiL5XvzsfvxnnY_3JMQxY9svps/1200x900/2021/08/27/phpLvR9jQ.jpg', 'Paris', '4', 'euro', '1h', ARRAY['magie', 'spectacle', 'enfants', 'insolite'], 'https://www.museedelamagie.com/', false),
('Musée Curie', 'Musée dédié à Marie Curie et à l''histoire de la radioactivité dans son ancien laboratoire.', 'musee', 'https://musee.curie.fr/.uploads/2018-05/plan-de-travail-7home-bbd028ab.png?ex=x-50.068_y-50.082_w-99.731_h-99.637&rs=z-100', 'Paris', '5', 'gratuit', '50 minutes', ARRAY['sciences', 'gratuit', 'curie', 'radioactivité'], 'https://musee.curie.fr/', false),
('Monnaie de Paris', 'Plus ancienne institution de France avec expositions sur l''art monétaire et ateliers créatifs.', 'musee', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwL2KlX2AeWgQ9IZ7HndhufXiAE86jtil4kw&s', 'Paris', '6', 'euro', '1h30', ARRAY['monnaie', 'histoire', 'seine', 'ateliers'], 'https://www.monnaiedeparis.fr/', false),
('Musée de la Vie Romantique', 'Maison-atelier de style romantique évoquant George Sand et la vie artistique du XIXe siècle.', 'musee', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi53yoL9m1G87mXObNXcHSk6vQsMIq29qiZ6hKnbr1QfmcD-P8PS0B79aqe1LPPD02zEcwor7Phx3noYCgNWC4Bvj7mAri39YVe0oQqVHrujwNFnIRLUZQVRttFgwdjpnFIniechUC0oenqdYwN0d3M9z38Zb4qLBIcQf5djNQulzYxo6Bl0woNDTqj9xo/w1200-h630-p-k-no-nu/musee-de-la-vie-romantique-rue-chaptal-paris-9-nouvelle-athenes-0.JPG', 'Paris', '9', 'euro', '1h30', ARRAY['romantisme', 'george-sand', 'xixe', 'jardin'], 'https://www.museevieromantique.paris.fr/', false),
('Musée des Arts Forains', 'Collection unique de manèges et attractions de fête foraine anciens, sur réservation.', 'musee', 'https://www.celoisirs.fr/wp-content/uploads/0089_ArtsForains-scaled.jpg', 'Paris', '12', 'euro', '2h', ARRAY['forain', 'manèges', 'vintage', 'insolite'], 'https://arts-forains.com/', false),
('Musée Vivant du Fromage', 'Exploration interactive de l''univers fromager avec caves d''affinage et dégustations.', 'musee', 'https://www.leguidedufromage.com/files/1/2406281904240.jpg', 'Paris', '4', 'euro', '2h30', ARRAY['fromage', 'gastronomie', 'dégustation', 'artisanat'], 'https://www.museedufromage.paris/', false),
('Égouts de Paris', 'Visite souterraine du réseau d''assainissement parisien, témoignage unique du génie civil.', 'musee', 'https://cdn.paris.fr/paris/2021/10/14/huge-6a309ea7125fee5702dd0e107d3d5c7c.jpg', 'Paris', '7', 'euro', '1h', ARRAY['souterrain', 'insolite', 'ingénierie', 'histoire'], 'https://www.paris.fr/', false),
('Palais Galliera', 'Musée de la Mode de la Ville de Paris avec expositions temporaires de haute couture.', 'musee', 'https://www.pariszigzag.fr/wp-content/uploads/2024/01/palais-galliera-musee-mode-paris-zigzag-1.jpg', 'Paris', '16', 'euro', '2h10', ARRAY['mode', 'couture', 'expositions', 'élégance'], 'https://www.palaisgalliera.paris.fr/', false),
('Musée de Cluny', 'Musée national du Moyen Âge avec la Dame à la Licorne et thermes gallo-romains.', 'musee', 'https://www.connaissancedesarts.com/wp-content/thumbnails/uploads/2022/05/gabarit-article-2-tt-width-1200-height-900-fill-0-crop-1-bgcolor-ffffff.jpg', 'Paris', '5', 'euro', '1h30', ARRAY['moyen-âge', 'licorne', 'thermes', 'tapisseries'], 'https://www.musee-moyenage.fr/', false),
('Institut du Monde Arabe', 'Architecture innovante de Jean Nouvel célébrant la culture arabo-musulmane.', 'musee', 'https://static.wixstatic.com/media/de5a6d_aa25a03c49ae442e9b303084fb0a4573~mv2.webp/v1/fill/w_607,h_392,al_c/de5a6d_aa25a03c49ae442e9b303084fb0a4573~mv2.webp', 'Paris', '5', 'euro', '1h', ARRAY['architecture', 'culture-arabe', 'nouvel', 'vue'], 'https://www.imarabe.org/', false),
('Grande Galerie de l''Évolution', 'Spectaculaire mise en scène de la biodiversité dans le Muséum national d''Histoire naturelle.', 'musee', 'https://s3.eu-west-3.amazonaws.com/content-mnhn-prod-secutix-xt6sxydl/images/catalog/product/large/6a1d0457-ca3e-4e38-82c1-9df6733de132.jpg', 'Paris', '5', 'euro', '2h15', ARRAY['nature', 'animaux', 'sciences', 'famille'], 'https://www.mnhn.fr/', false),
('Musée Nissim de Camondo', 'Hôtel particulier Belle Époque avec collection d''arts décoratifs du XVIIIe siècle.', 'musee', 'https://res.cloudinary.com/dtljonz0f/image/upload/c_auto,ar_3:1,w_3840,g_auto/f_auto/q_auto/v1/gc-v1/paris-pass/112?_a=BAVAZGGf0', 'Paris', '8', 'euro', '1h30', ARRAY['décoratifs', 'xviiie', 'monceau', 'élégance'], 'https://madparis.fr/', false),
('Musée Cognacq-Jay', 'Collection XVIIIe siècle des fondateurs de la Samaritaine dans un hôtel du Marais.', 'musee', 'https://www.museecognacqjay.paris.fr/sites/default/files/styles/590x445/public/2021-11/c_pierre_antoine_-_musee_cognacq-jay_30.jpg?h=0100f65f&itok=Sj7tGpkN', 'Paris', '3', 'euro', '45 minutes', ARRAY['xviiie', 'marais', 'peinture', 'décoratifs'], 'https://www.museecognacqjay.paris.fr/', false),
('Musée Marmottan Monet', 'Plus grande collection mondiale d''œuvres de Claude Monet dans un hôtel particulier.', 'musee', 'https://www.franceguide.info/fr/wp-content/uploads/sites/20/paris-musee-marmottan-monet-peintures-hd.jpg', 'Paris', '16', 'euro', '45 minutes', ARRAY['monet', 'impressionnisme', 'nymphéas', 'intime'], 'https://www.marmottan.fr/', false),
('Musée Cernuschi', 'Art asiatique dans un hôtel particulier avec jardin japonais près du Parc Monceau.', 'musee', 'https://www.cernuschi.paris.fr/sites/default/files/styles/767x511_scale_crop/public/salle-boudha_hd_1224_cernuschi_paris_musees_cpierre_antoine.jpg?itok=K-JwPrzj', 'Paris', '8', 'euro', '1h30', ARRAY['asie', 'japon', 'chine', 'monceau'], 'https://www.cernuschi.paris.fr/', false),
('Musée de Montmartre', 'Histoire du quartier bohème dans les ateliers où vécut Renoir, avec jardins du Renoir.', 'musee', 'https://oh-oui.com/musee-montmartre2/wp-content/uploads/sites/23/2021/07/Infos-pratiques.jpg', 'Paris', '18', 'euro', '2h', ARRAY['montmartre', 'bohème', 'renoir', 'jardins'], 'https://museedemontmartre.fr/', false),
('Palais de Tokyo', 'Centre d''art contemporain le plus grand d''Europe, ouvert jusqu''à minuit.', 'musee', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKES9tmJI7qZI9GjSC5LnKKRyWv2XNoe1zqg&s', 'Paris', '16', 'euro', '2h', ARRAY['contemporain', 'nocturne', 'expositions', 'avant-garde'], 'https://www.palaisdetokyo.com/', false),
('Musée d''Art Moderne de Paris', 'Collection majeure d''art des XXe et XXIe siècles dans l''aile est du Palais de Tokyo.', 'musee', 'https://files.offi.fr/lieu/1450/images/1000/edfef1cf02463aa59d320ad90d201de8.jpg', 'Paris', '16', 'euro', '1h30', ARRAY['art-moderne', 'xxe', 'peinture', 'sculpture'], 'https://www.mam.paris.fr/', false),
('Musée des Arts Décoratifs', 'Du Moyen Âge au design contemporain dans les ailes du Louvre sur les arts appliqués.', 'musee', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtr45mL92ujd2677eMJku8CKsWMIE1SLdgQA&s', 'Paris', '1', 'euro', '1h30', ARRAY['design', 'mobilier', 'mode', 'décoratifs'], 'https://madparis.fr/', false),
('Musée Rodin', 'Œuvres du sculpteur dans son hôtel particulier avec jardin de sculptures remarquable.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Le_musée_Rodin.jpg', 'Paris', '7', 'euro', '1h30', ARRAY['sculpture', 'rodin', 'jardin', 'penseur'], 'https://www.musee-rodin.fr/', false),
('Musée National des Arts Asiatiques - Guimet', 'Plus grande collection d''art asiatique hors d''Asie, des civilisations antiques à nos jours.', 'musee', 'https://www.unjourdeplusaparis.com/wp-content/uploads/2012/03/musee-guimet-990x602.jpg', 'Paris', '16', 'euro', '2h', ARRAY['asie', 'bouddha', 'extrême-orient', 'civilisations'], 'https://www.guimet.fr/', false),
('Musée de l''Air et de l''Espace', 'Plus ancien musée aéronautique au monde au Bourget avec avions mythiques et Concorde.', 'musee', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGeiRmu9bG0zKmMETaRCg8beYLxYQzqggdUg&s', 'Le Bourget', NULL, 'euro', '2h30', ARRAY['aviation', 'espace', 'concorde', 'sciences'], 'https://www.museeairespace.fr/', false),
('Musée Jacquemart-André', 'Collection exceptionnelle de maîtres italiens dans un hôtel particulier Second Empire.', 'musee', 'https://www.musee-jacquemart-andre.com/sites/default/files/styles/oeuvre_lightbox/public/2024-09/cour_musee_jacquemart-andre.jpg.webp?itok=iqTAaGXf', 'Paris', '8', 'euro', '1h15', ARRAY['italien', 'haussmann', 'peinture', 'salon-de-thé'], 'https://www.musee-jacquemart-andre.com/', false),
('Hôtel des Invalides', 'Chef-d''œuvre d''architecture classique abritant le tombeau de Napoléon et musées militaires.', 'musee', 'https://res.cloudinary.com/du5jifpgg/image/upload/t_opengraph_image/Headers%20rubriques%20Jeux%20Olympiques/que-faire-aux-invalides.jpg', 'Paris', '7', 'euro', '3h', ARRAY['napoléon', 'militaire', 'architecture', 'dôme'], 'https://www.musee-armee.fr/', false),
('Musée Zadkine', 'Atelier-musée du sculpteur Ossip Zadkine dans un jardin paisible de Montparnasse.', 'musee', 'https://musees-occitanie.fr/assets/uploads/2020/12/zad-zad-low.jpg', 'Paris', '6', 'euro', '1h', ARRAY['sculpture', 'zadkine', 'atelier', 'jardin'], 'https://www.zadkine.paris.fr/', false),
('Mémorial de la Shoah', 'Lieu de mémoire et musée consacré à l''histoire du génocide des Juifs pendant la Seconde Guerre mondiale.', 'musee', 'https://www.memorialdelashoah.org/wp-content/uploads/2016/04/crypte--jc-boussiquet-720x400.jpg', 'Paris', '4', 'gratuit', '1h30', ARRAY['mémoire', 'shoah', 'histoire', 'wwii'], 'http://www.memorialdelashoah.org/', false),
('Maison de Victor Hugo', 'Appartement de l''écrivain place des Vosges où il vécut 16 ans et écrivit Les Misérables.', 'musee', 'https://www.maisonsvictorhugo.paris.fr/sites/default/files/styles/850x567/public/images/2022-12/appart_victor_hugo_dsc4133.jpg?h=d2f37f86&itok=wFG49ktI', 'Paris', '4', 'gratuit', '1h', ARRAY['hugo', 'littérature', 'vosges', 'romantisme'], 'http://www.maisonsvictorhugo.paris.fr/', false),
('Musée Maillol', 'Collection d''art moderne centrée sur le sculpteur Aristide Maillol avec expositions temporaires.', 'musee', 'https://museemaillol.com/wp-content/uploads/2025/01/maillol-rodin-1024x683.webp', 'Paris', '7', 'euro', '2h', ARRAY['sculpture', 'maillol', 'art-moderne', 'expositions'], 'https://www.museemaillol.com/', false),
('Musée du Parfum Fragonard', 'Découverte gratuite de l''art de la parfumerie française et de son histoire.', 'musee', 'https://musee-parfum-paris.fragonard.com/wp-content/uploads/2020/07/escalier-musee-scribe-1200x.jpg', 'Paris', '9', 'gratuit', '1h30', ARRAY['parfum', 'gratuit', 'artisanat', 'senteurs'], 'https://musee-parfum-paris.fragonard.com/', false),
('Musée national de la Marine', 'Histoire maritime française rénovée avec maquettes de navires, tableaux et instruments.', 'musee', 'https://www.lejdd.fr/lmnr/var/jdd/public/media/image/2022/07/20/00/paris-decouvrez-le-futur-musee-de-la-marine.jpg?VersionId=cYN34MHvY.llp8W4hmoYYAAIa.wQGFG1', 'Paris', '16', 'euro', '1h30', ARRAY['marine', 'bateaux', 'histoire', 'océan'], 'https://www.musee-marine.fr/', false),
('Cité de l''Architecture et du Patrimoine', 'Plus grand centre au monde dédié à l''architecture, dans le Palais de Chaillot.', 'musee', 'https://www.citedelarchitecture.fr/sites/default/files/styles/diaporama/public/images/2021-12/ext_6.jpg?itok=-xrQtMcm', 'Paris', '16', 'euro', '2h', ARRAY['architecture', 'patrimoine', 'maquettes', 'urbanisme'], 'https://www.citedelarchitecture.fr/', false),
('Musée de l''Homme', 'Évolution de l''humanité et diversité des cultures dans le Palais de Chaillot.', 'musee', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/0f/d1/99/le-musee-de-l-homme-installe.jpg?w=1200&h=-1&s=1', 'Paris', '16', 'euro', '1h30', ARRAY['anthropologie', 'préhistoire', 'cultures', 'sciences'], 'https://www.museedelhomme.fr/', false),
('Musée du Chocolat Choco-Story', 'Histoire du cacao et du chocolat avec démonstrations et dégustations incluses.', 'musee', 'https://www.chausseliere.com/wp-content/uploads/2023/01/Museeduchocolat1_1200_800_1.webp', 'Paris', '10', 'euro', '1h30', ARRAY['chocolat', 'dégustation', 'gourmand', 'famille'], 'https://www.museeduchocolat.fr/', false),
('Musée du Chocolat + Dégustation', 'Visite complète avec dégustation premium de chocolats artisanaux.', 'musee', 'https://www.chausseliere.com/wp-content/uploads/2023/01/Museeduchocolat1_1200_800_1.webp', 'Paris', '10', 'euro2', '1h30', ARRAY['chocolat', 'dégustation', 'gourmand', 'atelier'], 'https://www.museeduchocolat.fr/', false),
('Cité des Sciences et de l''Industrie', 'Plus grand musée des sciences d''Europe avec Géode, planétarium et expositions interactives.', 'musee', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/da/10/19/la-cite-des-sciences.jpg?w=900&h=500&s=1', 'Paris', '19', 'euro', '1h30', ARRAY['sciences', 'interactif', 'famille', 'géode'], 'https://www.cite-sciences.fr/', false),
('Musée Bourdelle', 'Atelier-musée du sculpteur Antoine Bourdelle, élève de Rodin, avec jardin de sculptures.', 'musee', 'https://www.bourdelle.paris.fr/sites/default/files/2024-04/poi_3_photo_2.jpg', 'Paris', '15', 'euro', '1h30', ARRAY['sculpture', 'bourdelle', 'atelier', 'montparnasse'], 'https://www.bourdelle.paris.fr/', false),
('Muséum national d''Histoire naturelle', 'Institution scientifique tricentenaire avec galeries, serres et ménagerie au Jardin des Plantes.', 'musee', 'https://media.timeout.com/images/100007393/image.jpg', 'Paris', '5', 'euro', '2h', ARRAY['nature', 'sciences', 'animaux', 'serres'], 'https://www.mnhn.fr/', false),
('Espace Dalí', 'Collection surréaliste de Salvador Dalí avec sculptures et gravures au cœur de Montmartre.', 'musee', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/7d/68/45/entree-du-musee.jpg?w=900&h=500&s=1', 'Paris', '18', 'euro', '1h', ARRAY['dalí', 'surréalisme', 'montmartre', 'sculptures'], 'https://daliparis.com/', false),
('Musée du quai Branly - Jacques Chirac', 'Arts et civilisations d''Afrique, Asie, Océanie et Amériques dans une architecture végétalisée.', 'musee', 'https://www.cometoparis.com/data/layout_grouping/product_index_slideshow/59629_musee-du-quai-branly-jacques-chirac.1000w.jpg?ver=1675417884', 'Paris', '7', 'euro', '2h30', ARRAY['ethnologie', 'arts-premiers', 'nouvel', 'jardins'], 'https://www.quaibranly.fr/', false);

-- EXPOSITIONSx
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website, already_done) VALUES
('Atelier des Lumières', 'Expériences immersives monumentales dans une ancienne fonderie, projections à 360°.', 'expo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQObDKM7gujyyb6DO8xCaIQIKuI-OtvHF4DKw&s', 'Paris', '11', 'euro', '1h30', ARRAY['immersif', 'numérique', 'art', 'spectacle'], 'https://www.atelier-lumieres.com/', false),
('Bourse de Commerce - Collection Pinault', 'Art contemporain dans un monument historique restauré par Tadao Ando.', 'expo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7qt1H57CJjLDTC7MYD8nYxPDoJXp2XdauwQ&s', 'Paris', '1', 'euro', '1h30', ARRAY['contemporain', 'pinault', 'ando', 'architecture'], 'https://www.pinaultcollection.com/boursedecommerce', false),
('Centre Pompidou', 'Architecture high-tech iconique abritant le MNAM, la plus grande collection d''art moderne d''Europe.', 'expo', 'https://www.egfbtp.com/wp-content/uploads/2021/06/centre_georges_pompidou.jpg', 'Paris', '4', 'euro', '2h', ARRAY['art-moderne', 'architecture', 'piano-rogers', 'expositions'], 'https://www.centrepompidou.fr/', false);

-- SPECTACLES
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website, already_done) VALUES
('Moulin Rouge', 'Légendaire cabaret parisien depuis 1889 avec le célèbre French Cancan et revue Féerie.', 'spectacle', 'https://www.nyc.fr/wp-content/uploads/2023/11/salle-moulin-rouge-scaled.jpg', 'Paris', '18', 'euro3', '1h40', ARRAY['cabaret', 'french-cancan', 'mythique', 'soirée'], 'https://www.moulinrouge.fr/', false),
('Lido de Paris', 'Cabaret des Champs-Élysées avec spectacle et option dîner au Fouquet''s.', 'spectacle', 'https://cdn.paris.fr/paris/2025/05/15/huge-8fdd3a47eff6cb83805ffa69a0f9e0d0.png', 'Paris', '8', 'euro2', '2h30', ARRAY['cabaret', 'champs-élysées', 'dîner', 'revue'], 'https://www.lido-paris.com/', false),
('Folies Bergères', 'Salle de spectacles mythique accueillant concerts, one-man shows et comédies musicales.', 'spectacle', 'https://www.foliesbergere.com/sites/hubber_site_foliesbergere8/files/inline-images/capture-decran-2024-01-02-a-12.24.06.jpg', 'Paris', '9', 'euro2', NULL, ARRAY['spectacle', 'variétés', 'mythique', 'concerts'], 'https://www.foliesbergere.com/', false);

-- QUARTIERS
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website, already_done) VALUES
('Quartier Châtelet', 'Cœur historique de Paris entre théâtres, fontaine de la Victoire et rues commerçantes.', 'quartier', 'https://voyagesdecidela.com/wp-content/uploads/2022/04/Voyages-Deci-Dela-Paris-1er-arrondissement-chatelet-les-halles-grands-magasins.jpg', 'Paris', '1', 'gratuit', NULL, ARRAY['centre', 'théâtres', 'shopping', 'histoire'], NULL, false),
('Montmartre', 'Village bohème avec le Sacré-Cœur, vignes, artistes de rue et cafés légendaires.', 'quartier', 'https://www.cometoparis.com/data/layout_image/475_sacré%20coeur_landscape_3-2_xl.jpg?ver=1739891695', 'Paris', '18', 'gratuit', NULL, ARRAY['bohème', 'sacré-coeur', 'artistes', 'romantique'], NULL, false),
('Cimetière du Père-Lachaise', 'Plus grand cimetière de Paris avec tombes de célébrités dans un décor romantique.', 'quartier', 'https://cdn.paris.fr/paris/2023/11/23/original-d8aebf44f2d129aa652478ad4cb3dab7.jpg', 'Paris', '20', 'gratuit', NULL, ARRAY['cimetière', 'célébrités', 'romantique', 'promenade'], 'https://pere-lachaise.com/', false),
('Place Vendôme', 'Place octogonale prestigieuse avec colonne Vendôme et joailliers de luxe.', 'quartier', 'https://tourguide-france.com/wp-content/uploads/elementor/thumbs/Place-Vendome-in-Paris-qf3gh6bx2bu7pp27vcc4ljco6xhr54imzkhr2habmg.jpg', 'Paris', '1', 'gratuit', NULL, ARRAY['luxe', 'joaillerie', 'napoléon', 'élégance'], NULL, false),
('Le Marais', 'Quartier historique avec hôtels particuliers, musées, boutiques branchées et communauté LGBT.', 'quartier', 'https://www.junot.fr/upload/images/image_block_images/6530fdd0c1a1a5.94623904_rue_des_francs_bourgeois_final_mg_7519_copie.webp', 'Paris', '4', 'gratuit', NULL, ARRAY['historique', 'shopping', 'lgbt', 'vosges'], NULL, false),
('Champs-Élysées', 'La plus belle avenue du monde entre Arc de Triomphe et Place de la Concorde.', 'quartier', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2SM8LQzC5M-rBeiQUvydqofpQeNj3bNw04g&s', 'Paris', '8', 'gratuit', NULL, ARRAY['célèbre', 'shopping', 'arc-triomphe', 'promenade'], NULL, true),
('Île de la Cité', 'Berceau historique de Paris avec Notre-Dame, Sainte-Chapelle et Conciergerie.', 'quartier', 'https://arcanum.paris/uploads/insolite/405/ile-de-la-cite-panorama-paris-secret-insolite-arcanum.jpg', 'Île de la Cité', NULL, 'gratuit', NULL, ARRAY['histoire', 'notre-dame', 'origines', 'gothique'], NULL, false),
('Quartier Latin', 'Quartier étudiant historique avec universités, librairies, cinémas et vie nocturne.', 'quartier', 'https://www.tourleader.net/images/parigi/quartieri/quartiere-latino.jpg', 'Paris', '5', 'gratuit', NULL, ARRAY['étudiant', 'universités', 'librairies', 'animation'], NULL, true),
('Canal Saint-Martin', 'Canal romantique bordé de platanes avec écluses, passerelles et terrasses branchées.', 'quartier', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiQDYgtUyU3cnJelW_ZL_eOnTw9CA_bmh9LQ&s', 'Paris', '10', 'gratuit', NULL, ARRAY['romantique', 'canal', 'terrasses', 'branché'], NULL, false),
('Quartier Opéra', 'Quartier haussmannien autour du Palais Garnier avec grands magasins et passages couverts.', 'quartier', 'https://www.parisselectbook.com/wp-content/uploads/2024/07/quartieropera.jpeg-edited.webp', 'Paris', '9', 'gratuit', NULL, ARRAY['opéra', 'haussmann', 'shopping', 'passages'], NULL, false),
('Grands Boulevards', 'Artères animées avec théâtres, cinémas, passages couverts et architecture XIXe.', 'quartier', 'https://paris1900.lartnouveau.com/mini3/mini3_gb/1bdcapuc1.JPG', 'Paris', '2', 'gratuit', NULL, ARRAY['animation', 'théâtres', 'passages', 'xixe'], NULL, false),
('Quartier du Louvre', 'Autour du plus grand musée du monde, entre Palais Royal et Pont des Arts.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/1280px-Louvre_Museum_Wikimedia_Commons.jpg', 'Paris', '1', 'gratuit', NULL, ARRAY['louvre', 'culture', 'pyramide', 'seine'], NULL, false),
('Quartier Tour Eiffel / Trocadéro', 'Icône de Paris avec esplanades, fontaines et vue exceptionnelle sur la Dame de Fer.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg', 'Paris', '7', 'gratuit', NULL, ARRAY['tour-eiffel', 'iconique', 'vue', 'photo'], NULL, true),
('Bastille', 'Quartier populaire historique devenu branché avec vie nocturne, marché et opéra moderne.', 'quartier', 'https://www.travelguide.fr/media/paris-place-de-la-bastille.jpg', 'Paris', '4', 'gratuit', NULL, ARRAY['révolution', 'nocturne', 'branché', 'marché'], NULL, false),
('Quartier Asiatique', 'Le plus grand Chinatown d''Europe avec restaurants, commerces et culture asiatique.', 'quartier', 'https://pariscrea.com/wp-content/uploads/2024/01/visiter-quartier-chinois-paris-portes.jpg', 'Paris', '13', 'gratuit', NULL, ARRAY['asiatique', 'gastronomie', 'chinatown', 'authentique'], NULL, false),
('Promenade Louvre - Champs-Élysées', 'Balade mythique traversant Tuileries, Concorde et remontant la plus belle avenue du monde.', 'quartier', 'https://www.thetrainline.com/cms/media/4040/europe_france_paris_champs-elysees.jpg?mode=crop&width=660&height=440&quality=70', 'Paris', '1', 'gratuit', '45 minutes', ARRAY['promenade', 'iconique', 'tuileries', 'concorde'], NULL, true),
('Esplanade du Trocadéro', 'Point de vue emblématique sur la Tour Eiffel avec jardins et fontaines monumentales.', 'quartier', 'https://d2iru24ttzll0d.cloudfront.net/cache/img/7def92be41d8b4a60e5ca6e661fa77d2b494b339-7def92-1024-383-landscape.jpg?q=1688655331', 'Paris', '16', 'gratuit', '30 minutes', ARRAY['vue', 'tour-eiffel', 'fontaines', 'photo'], NULL, true);

-- TOURISME HISTORIQUE
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website, already_done) VALUES
('Sacré-Cœur (Basilique)', 'Basilique romano-byzantine dominant Paris depuis la butte Montmartre, accès gratuit.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Le_sacre_coeur.jpg/1024px-Le_sacre_coeur.jpg', 'Paris', '18', 'gratuit', '1h', ARRAY['basilique', 'montmartre', 'vue', 'religieux'], 'https://www.sacre-coeur-montmartre.com/', false),
('Sacré-Cœur (Dôme)', 'Montée au dôme pour une vue panoramique exceptionnelle sur Paris à 360°.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Le_sacre_coeur.jpg/1024px-Le_sacre_coeur.jpg', 'Paris', '18', 'euro', '1h30', ARRAY['panorama', 'montmartre', 'vue', 'dôme'], 'https://www.sacre-coeur-montmartre.com/', false),
('Invalides (Extérieurs)', 'Promenade gratuite autour du monument et de son esplanade avec vue sur le dôme doré.', 'tourisme_historique', 'https://res.cloudinary.com/du5jifpgg/image/upload/t_opengraph_image/Headers%20rubriques%20Jeux%20Olympiques/que-faire-aux-invalides.jpg', 'Paris', '7', 'gratuit', '1h', ARRAY['napoléon', 'dôme', 'militaire', 'promenade'], 'https://www.musee-armee.fr/', false),
('Tour Eiffel (Sans montée)', 'Admirer la Dame de Fer depuis le Champ de Mars et le Trocadéro, gratuitement.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg', 'Tour Eiffel', '7', 'gratuit', '30 minutes', ARRAY['tour-eiffel', 'iconique', 'photo', 'gratuit'], 'https://www.toureiffel.paris/', true),
('Tour Eiffel 2ème étage (Ascenseur)', 'Montée en ascenseur jusqu''au 2ème étage avec vue spectaculaire sur Paris.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg', 'Tour Eiffel', '7', 'euro2', '1h30', ARRAY['tour-eiffel', 'vue', 'ascenseur', 'incontournable'], 'https://www.toureiffel.paris/', false),
('Tour Eiffel 2ème étage (Escalier)', 'Montée sportive à pied pour une expérience unique avec accès aux piliers historiques.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg', 'Tour Eiffel', '7', 'euro', '2h', ARRAY['tour-eiffel', 'sport', 'escalier', 'économique'], 'https://www.toureiffel.paris/', false),
('Conciergerie', 'Prison révolutionnaire dans le Palais de la Cité, dernière demeure de Marie-Antoinette.', 'tourisme_historique', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShifTUbP6d4yw1JubjI153UoJucacyyhL7mQ&s', 'Paris', '1', 'euro', '1h', ARRAY['révolution', 'prison', 'médiéval', 'histoire'], 'http://www.paris-conciergerie.fr/', false),
('Panthéon (Extérieurs)', 'Admirez le monument néoclassique abritant les grands Hommes depuis la place du Panthéon.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Pantheon_of_Paris_007.JPG/1280px-Pantheon_of_Paris_007.JPG', 'Panthéon', '5', 'gratuit', '30 minutes', ARRAY['néoclassique', 'grands-hommes', 'quartier-latin', 'architecture'], 'http://www.paris-pantheon.fr/', true),
('Panthéon (Visite)', 'Visite du monument avec crypte des personnalités illustres et pendule de Foucault.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Pantheon_of_Paris_007.JPG/1280px-Pantheon_of_Paris_007.JPG', 'Panthéon', '5', 'euro', '2h', ARRAY['crypte', 'foucault', 'histoire', 'grands-hommes'], 'http://www.paris-pantheon.fr/', false),
('Assemblée Nationale', 'Visite gratuite du Palais Bourbon, siège de la démocratie française depuis 1798.', 'tourisme_historique', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQU3rdytkD9ryB85M3OHCrX2gWSMvvEeH9IsQ&s', 'Paris', '7', 'gratuit', '1h30', ARRAY['politique', 'démocratie', 'palais-bourbon', 'gratuit'], 'https://www.assemblee-nationale.fr/', false),
('Opéra Garnier (Sans guide)', 'Visite libre du chef-d''œuvre de Charles Garnier avec grand escalier et plafond Chagall.', 'tourisme_historique', 'https://res.cloudinary.com/dtljonz0f/image/upload/palais_garnier_banner_non_editorial_l6t3th', 'Paris', '9', 'euro', '1h30', ARRAY['opéra', 'garnier', 'chagall', 'architecture'], 'https://www.operadeparis.fr/', false),
('Opéra Garnier (Avec guide)', 'Visite guidée approfondie révélant les secrets et l''histoire du Palais Garnier.', 'tourisme_historique', 'https://res.cloudinary.com/dtljonz0f/image/upload/palais_garnier_banner_non_editorial_l6t3th', 'Paris', '9', 'euro2', '1h30', ARRAY['opéra', 'garnier', 'guidée', 'secrets'], 'https://www.operadeparis.fr/', false),
('Arc de Triomphe (Extérieurs)', 'Admirer le monument napoléonien et la flamme du Soldat inconnu gratuitement.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg/1024px-Arc_de_Triomphe%2C_Paris_21_October_2010.jpg', 'Paris', '8', 'gratuit', '30 minutes', ARRAY['napoléon', 'étoile', 'champs-élysées', 'monument'], NULL, false),
('Arc de Triomphe (Visite)', 'Montée sur la terrasse panoramique offrant une vue à 360° sur Paris et ses avenues.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg/1024px-Arc_de_Triomphe%2C_Paris_21_October_2010.jpg', 'Paris', '8', 'euro2', '1h', ARRAY['panorama', 'napoléon', 'vue', 'champs-élysées'], 'http://www.paris-arc-de-triomphe.fr/', false),
('Sainte-Chapelle', 'Joyau gothique rayonnant avec vitraux du XIIIe siècle exceptionnels.', 'tourisme_historique', 'https://cdn-imgix.headout.com/media/images/7178aa88d4ec8f7fec3c4ae6a6aad012-26700-paris-paris-highlights-guided-tour-of-notre-dame-island-with-entry-to-sainte-chapelle-06.jpeg.jpg?auto=format&q=90&crop=faces&fit=crop', 'Paris', '1', 'euro', '1h', ARRAY['gothique', 'vitraux', 'île-de-la-cité', 'chef-d-oeuvre'], 'http://www.sainte-chapelle.fr/', false),
('Notre-Dame (Sans montée)', 'Visite gratuite de la cathédrale restaurée après l''incendie de 2019.', 'tourisme_historique', 'https://www.cometoparis.com/data/layout_image/20792_0bd10b87f37ed3c3edf836e8b8f5a254_landscape_3-2_xl.jpg?ver=1738235519', 'Île de la Cité', '4', 'gratuit', '1h', ARRAY['cathédrale', 'gothique', 'gratuit', 'histoire'], 'https://www.notredamedeparis.fr/', true),
('Notre-Dame (Avec montée tours)', 'Ascension des tours pour voir les gargouilles et la vue sur Paris.', 'tourisme_historique', 'https://www.cometoparis.com/data/layout_image/20792_0bd10b87f37ed3c3edf836e8b8f5a254_landscape_3-2_xl.jpg?ver=1738235519', 'Île de la Cité', '4', 'euro', '2h', ARRAY['cathédrale', 'tours', 'gargouilles', 'panorama'], 'https://www.notredamedeparis.fr/', false),
('Tour Montparnasse', 'Vue panoramique à 210m de haut, la meilleure vue sur Paris avec la Tour Eiffel.', 'tourisme_historique', 'https://france3-regions.franceinfo.fr/image/F9U0Qlc5If1SPjEieptDpndBWhU/1200x1200/regions/2023/04/07/6430200c9a967_maxnewsspecial461316.jpg', 'Quartier Montparnasse', '15', 'euro2', '1h', ARRAY['panorama', 'vue', 'moderne', 'terrasse'], 'https://www.tourmontparnasse56.com/', true),
('Bibliothèque National de France Richelieu', 'Bibliothèque historique avec salle de lecture ovale magnifique et expositions.', 'tourisme_historique', 'https://www.bnf.fr/sites/default/files/2022-08/BNF_2022_148261MD_BD.jpg', 'Paris', '2', 'euro', '1h30', ARRAY['bibliothèque', 'architecture', 'culture', 'livres'], 'https://www.bnf.fr/', false);

-- AUTRES
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website, already_done) VALUES
('Bus Touristique', 'Découverte de Paris en bus à impériale avec commentaires et arrêts multiples.', 'autre', 'https://www.civitatis.com/f/francia/paris/autobus-turistico-paris-589x392.jpg', 'Paris', NULL, 'euro2', '1h30', ARRAY['bus', 'tour', 'commentaires', 'pratique'], 'https://www.bigbustours.com/', false),
('E-Motion', 'Expériences de réalité virtuelle et simulateurs de sensations fortes.', 'autre', 'https://www.largus.fr/images/styles/max_1300x1300/public/2025-06/centre-e-motion-paris-car-lovers-the-grid-002_9.jpg?itok=wAyFlRe-', 'Paris', '2', 'euro2', '15-30 minutes', ARRAY['vr', 'simulateur', 'sensations', 'technologie'], NULL, false),
('Catacombes de Paris', 'Ossuaire souterrain contenant les restes de 6 millions de Parisiens.', 'autre', 'https://cdn-imgix.headout.com/media/images/e3ed04b94b7a66ed9e4658556a42dcf2-253-Paris-Catacombs-Tour-and-Tickets-01.jpg', 'Paris', '14', 'euro', '1h30', ARRAY['souterrain', 'ossuaire', 'insolite', 'histoire'], 'https://www.catacombes.paris.fr/', false),
('Galeries Lafayette Haussmann', 'Grand magasin emblématique avec coupole Art Nouveau et terrasse panoramique gratuite.', 'autre', 'https://www.exp1.com/wp-content/uploads/sites/7/2020/07/Interior-of-Galeries-Lafayette-shown-floor-by-floor.jpg', 'Paris', '9', 'gratuit', NULL, ARRAY['shopping', 'coupole', 'gratuit', 'vue'], 'https://www.galerieslafayette.com/', false);