-- Seed file for Paris activities
-- Generated from provided data
-- price_range: gratuit | euro (<20€) | euro2 (20-50€) | euro3 (>50€)

-- JARDINS (Gardens) - Tous gratuits
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website) VALUES
('Jardin Montsouris', 'Magnifique parc à l''anglaise de 15 hectares avec pelouses vallonnées, lac et sculptures. Idéal pour pique-niques et promenades.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Parc_Montsouris_-_lac.jpg/1280px-Parc_Montsouris_-_lac.jpg', 'Paris', '14', 'gratuit', NULL, ARRAY['nature', 'famille', 'pique-nique', 'lac'], 'https://www.paris.fr/lieux/parc-montsouris-1810'),
('Jardin des Tuileries', 'Jardin historique créé au XVIe siècle, reliant le Louvre à la place de la Concorde. Sculptures, bassins et chaises emblématiques.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Tuileries_Garden%2C_Paris_13_June_2012.jpg/1280px-Tuileries_Garden%2C_Paris_13_June_2012.jpg', 'Paris', '1', 'gratuit', NULL, ARRAY['histoire', 'sculptures', 'centre-ville', 'romantique'], 'https://www.louvre.fr/en/explore/the-palace/the-tuileries-garden'),
('Jardin du Palais Royal', 'Écrin de verdure entouré d''arcades élégantes. Un havre de paix au cœur de Paris avec les colonnes de Buren.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Palais_Royal_Garten.jpg/1280px-Palais_Royal_Garten.jpg', 'Paris', '1', 'gratuit', NULL, ARRAY['histoire', 'architecture', 'calme', 'centre-ville'], 'https://www.domaine-palais-royal.fr/'),
('Jardins du Trocadéro', 'Jardins offrant une vue imprenable sur la Tour Eiffel, avec fontaines spectaculaires et architecture Art Déco.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Eiffel_Tower_from_the_Trocadero.jpg/1280px-Eiffel_Tower_from_the_Trocadero.jpg', 'Paris', '16', 'gratuit', NULL, ARRAY['tour-eiffel', 'fontaines', 'vue', 'photo'], 'https://www.paris.fr/lieux/jardins-du-trocadero-1783'),
('Parc Floral de Paris', 'Le plus grand jardin botanique de Paris avec collections de plantes, aires de jeux et concerts en été.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Parc_floral_de_Paris_-_Jardin_des_iris_01.jpg/1280px-Parc_floral_de_Paris_-_Jardin_des_iris_01.jpg', 'Paris', '12', 'gratuit', NULL, ARRAY['botanique', 'fleurs', 'famille', 'concerts'], 'https://www.paris.fr/lieux/parc-floral-de-paris-1808'),
('Parc Monceau', 'Parc romantique du XVIIIe siècle avec fausses ruines, colonnade corinthienne et atmosphère bucolique.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/France_-_Paris_%288%29_-_Parc_Monceau.JPG/1280px-France_-_Paris_%288%29_-_Parc_Monceau.JPG', 'Paris', '8', 'gratuit', NULL, ARRAY['romantique', 'histoire', 'ruines', 'élégant'], 'https://www.paris.fr/lieux/parc-monceau-1804'),
('Parc de Bercy', 'Ancien site viticole transformé en parc contemporain avec jardins thématiques, passerelle et vignes.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Bercy_park%2C_Paris_12.jpg/1280px-Bercy_park%2C_Paris_12.jpg', 'Paris', '12', 'gratuit', NULL, ARRAY['moderne', 'vignes', 'famille', 'sport'], 'https://www.paris.fr/lieux/parc-de-bercy-1792'),
('Parc de la Villette', 'Le plus grand parc de Paris avec Cité des Sciences, Géode, Philharmonie et nombreuses activités culturelles.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Paris_-_Parc_de_la_Villette_-_G%C3%A9ode_-_1.jpg/1280px-Paris_-_Parc_de_la_Villette_-_G%C3%A9ode_-_1.jpg', 'Paris', '19', 'gratuit', NULL, ARRAY['culture', 'sciences', 'concerts', 'famille'], 'https://lavillette.com/'),
('Parc Clichy-Batignolles Martin Luther King', 'Parc écologique moderne avec jardins partagés, skatepark et architecture contemporaine.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Parc_Clichy-Batignolles_-_Martin-Luther-King%2C_Paris_17e_1.jpg/1280px-Parc_Clichy-Batignolles_-_Martin-Luther-King%2C_Paris_17e_1.jpg', 'Paris', '17', 'gratuit', NULL, ARRAY['écologique', 'moderne', 'skatepark', 'famille'], 'https://www.paris.fr/lieux/parc-clichy-batignolles-martin-luther-king-1798'),
('Parc de l''Île Saint-Germain', 'Île verdoyante sur la Seine avec la Tour aux Figures de Jean Dubuffet et espaces de détente.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Tour_aux_figures_1.jpg/800px-Tour_aux_figures_1.jpg', 'Issy-les-Moulineaux', NULL, 'gratuit', NULL, ARRAY['île', 'sculpture', 'nature', 'tranquille'], 'https://www.issy.com/nature-proprete/nature-en-ville/ile-saint-germain'),
('Domaine National de Saint-Cloud', 'Immense domaine royal de 460 hectares avec jardins à la française, cascades et vue panoramique sur Paris.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Parc_de_Saint-Cloud_-_Grande_cascade_02.jpg/1280px-Parc_de_Saint-Cloud_-_Grande_cascade_02.jpg', 'Saint-Cloud', NULL, 'gratuit', NULL, ARRAY['domaine-royal', 'panorama', 'cascades', 'histoire'], 'http://www.domaine-saint-cloud.fr/'),
('Parc Edmond de Rothschild', 'Parc paysager de style anglais avec étang, cascades et arbres centenaires à Boulogne-Billancourt.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Parc_de_Boulogne_Edmond_de_Rothschild_%284%29.JPG/1280px-Parc_de_Boulogne_Edmond_de_Rothschild_%284%29.JPG', 'Boulogne-Billancourt', NULL, 'gratuit', NULL, ARRAY['anglais', 'étang', 'arbres', 'calme'], 'https://www.boulognebillancourt.com/'),
('Jardin du Ruisseau', 'Jardin associatif caché sur une ancienne voie ferrée de la Petite Ceinture. Un secret bien gardé du 18e.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Petite_ceinture_18e_3.jpg/1280px-Petite_ceinture_18e_3.jpg', 'Paris', '18', 'gratuit', NULL, ARRAY['associatif', 'secret', 'petite-ceinture', 'alternatif'], 'https://lejardinduruisseau.org/'),
('Les Plus Beaux Jardins de France', 'Espace vert élégant près des Champs-Élysées célébrant l''art des jardins français.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/P1000553_Paris_VIII_Jardin_des_Champs-Elys%C3%A9es_reducance.JPG/1280px-P1000553_Paris_VIII_Jardin_des_Champs-Elys%C3%A9es_reducance.JPG', 'Paris', '8', 'gratuit', NULL, ARRAY['élégant', 'champs-élysées', 'français'], 'https://www.paris.fr/'),
('Parc de la Vallée aux Loups', 'Arboretum romantique de 13 hectares avec collections botaniques exceptionnelles et maison de Chateaubriand.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Maison_de_Chateaubriand_01.jpg/1280px-Maison_de_Chateaubriand_01.jpg', 'Châtenay-Malabry', NULL, 'gratuit', NULL, ARRAY['arboretum', 'romantique', 'littérature', 'botanique'], 'https://vallee-aux-loups.hauts-de-seine.fr/'),
('Coulée Verte René-Dumont', 'Promenade plantée de 4,7 km sur une ancienne voie ferrée, précurseur de la High Line de New York.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Coul%C3%A9e_verte_Ren%C3%A9-Dumont%2C_Paris_12e%2C_pont_de_Reuilly.jpg/1280px-Coul%C3%A9e_verte_Ren%C3%A9-Dumont%2C_Paris_12e%2C_pont_de_Reuilly.jpg', 'Paris', '12', 'gratuit', NULL, ARRAY['promenade', 'voie-ferrée', 'original', 'marche'], 'https://www.paris.fr/lieux/coulee-verte-rene-dumont-ex-promenade-plantee-1784'),
('Parc de Belleville', 'Parc en terrasses offrant l''un des plus beaux panoramas sur Paris, avec vignes et cascades.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Vue_depuis_parc_de_Belleville.jpg/1280px-Vue_depuis_parc_de_Belleville.jpg', 'Paris', '20', 'gratuit', NULL, ARRAY['panorama', 'terrasses', 'vignes', 'vue'], 'https://www.paris.fr/lieux/parc-de-belleville-1791'),
('Parc des Buttes-Chaumont', 'Parc romantique du XIXe siècle avec lac, grottes, cascades et temple de la Sibylle perché sur un rocher.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Parc_des_Buttes-Chaumont%2C_Paris_19e%2C_France_003.JPG/1280px-Parc_des_Buttes-Chaumont%2C_Paris_19e%2C_France_003.JPG', 'Paris', '19', 'gratuit', NULL, ARRAY['romantique', 'lac', 'grottes', 'temple'], 'https://www.paris.fr/lieux/parc-des-buttes-chaumont-1757'),
('Jardin des Plantes', 'Plus ancien jardin botanique de France avec serres tropicales, ménagerie et Muséum d''Histoire naturelle.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Grande_galerie_de_l%27%C3%A9volution_-_vue_ext%C3%A9rieure.JPG/1280px-Grande_galerie_de_l%27%C3%A9volution_-_vue_ext%C3%A9rieure.JPG', 'Paris', '5', 'gratuit', NULL, ARRAY['botanique', 'serres', 'zoo', 'sciences'], 'https://www.jardindesplantesdeparis.fr/'),
('Jardin du Luxembourg', 'Jardin emblématique de Paris avec son palais, bassins, statues et atmosphère unique du Quartier Latin.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Le_Jardin_du_Luxembourg%2C_Paris%2C_France.jpg/1280px-Le_Jardin_du_Luxembourg%2C_Paris%2C_France.jpg', 'Paris', '6', 'gratuit', NULL, ARRAY['emblématique', 'palais', 'quartier-latin', 'romantique'], 'https://www.senat.fr/visite/jardin/'),
('Jardin Atlantique', 'Jardin suspendu au-dessus des voies de la gare Montparnasse, oasis de verdure inattendue.', 'jardin', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Jardin_atlantique_Paris.jpg/1280px-Jardin_atlantique_Paris.jpg', 'Gare Montparnasse', '15', 'gratuit', '1h30', ARRAY['suspendu', 'moderne', 'insolite', 'gare'], 'https://www.paris.fr/lieux/jardin-atlantique-1782');

-- PARCS D'ATTRACTIONS
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website) VALUES
('Jardin d''Acclimatation', 'Parc d''attractions familial historique au cœur du Bois de Boulogne avec manèges, ferme et jardins.', 'parc', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Jardin_d%27Acclimatation%2C_Paris_16e%2C_France.jpg/1280px-Jardin_d%27Acclimatation%2C_Paris_16e%2C_France.jpg', 'Paris', '16', 'euro2', 'journée', ARRAY['attractions', 'famille', 'manèges', 'animaux'], 'https://www.jardindacclimatation.fr/'),
('Disneyland Paris - 1 jour', 'Le célèbre parc à thèmes Disney avec deux parcs, attractions magiques et spectacles féeriques.', 'parc', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Sleeping_Beauty_Castle%2C_Disneyland%2C_Paris.jpg/1280px-Sleeping_Beauty_Castle%2C_Disneyland%2C_Paris.jpg', 'Marne-la-Vallée', NULL, 'euro3', '1 jour', ARRAY['disney', 'attractions', 'magie', 'famille'], 'https://www.disneylandparis.com/'),
('Disneyland Paris - 2 jours', 'Profitez de deux jours pour explorer les deux parcs Disney et vivre la magie sans vous presser.', 'parc', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Sleeping_Beauty_Castle%2C_Disneyland%2C_Paris.jpg/1280px-Sleeping_Beauty_Castle%2C_Disneyland%2C_Paris.jpg', 'Marne-la-Vallée', NULL, 'euro3', '2 jours', ARRAY['disney', 'attractions', 'magie', 'famille'], 'https://www.disneylandparis.com/'),
('Aquaboulevard', 'Le plus grand parc aquatique urbain d''Europe avec piscines à vagues, toboggans et espaces détente.', 'parc', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Logo_Aquaboulevard.svg/1280px-Logo_Aquaboulevard.svg.png', 'Paris', '15', 'euro2', 'journée', ARRAY['aquatique', 'piscine', 'toboggans', 'famille'], 'https://www.aquaboulevard.fr/');

-- CHÂTEAUX
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website) VALUES
('Château de Vincennes', 'Imposante forteresse médiévale avec le plus haut donjon de France et la Sainte-Chapelle.', 'chateau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Donjon_du_ch%C3%A2teau_de_Vincennes.jpg/1280px-Donjon_du_ch%C3%A2teau_de_Vincennes.jpg', 'Vincennes', NULL, 'euro', 'journée', ARRAY['médiéval', 'donjon', 'histoire', 'forteresse'], 'http://www.chateau-vincennes.fr/'),
('Château de Versailles', 'L''emblématique résidence royale avec ses jardins à la française, galerie des Glaces et Trianons.', 'chateau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Ch%C3%A2teau_de_Versailles%2C_October_2012.jpg/1280px-Ch%C3%A2teau_de_Versailles%2C_October_2012.jpg', 'Versailles', NULL, 'euro2', 'journée', ARRAY['royal', 'jardins', 'louis-xiv', 'unesco'], 'https://www.chateauversailles.fr/'),
('Château de Chantilly', 'Joyau Renaissance abritant le musée Condé, deuxième collection de peintures anciennes de France.', 'chateau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Chateau_de_Chantilly_garden.jpg/1280px-Chateau_de_Chantilly_garden.jpg', 'Chantilly', NULL, 'euro', 'journée', ARRAY['renaissance', 'musée', 'jardins', 'équitation'], 'https://www.chateaudechantilly.fr/'),
('Château de Fontainebleau', 'Résidence royale de 800 ans d''histoire, de François Ier à Napoléon III, avec forêt majestueuse.', 'chateau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Chateau_Fontainebleau.jpg/1280px-Chateau_Fontainebleau.jpg', 'Fontainebleau', NULL, 'euro', 'journée', ARRAY['royal', 'napoléon', 'forêt', 'histoire'], 'https://www.chateaudefontainebleau.fr/'),
('Château de Rambouillet', 'Ancienne résidence présidentielle avec parc de 100 hectares, laiterie de la Reine et chaumière.', 'chateau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Chateau_de_Rambouillet.jpg/1280px-Chateau_de_Rambouillet.jpg', 'Rambouillet', NULL, 'euro', 'journée', ARRAY['présidentiel', 'parc', 'histoire', 'nature'], 'http://www.chateau-rambouillet.fr/'),
('Château de Champs-sur-Marne', 'Élégant château du XVIIIe siècle avec intérieurs raffinés et jardins à la française remarquables.', 'chateau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Chateau_de_Champs-sur-Marne_001.jpg/1280px-Chateau_de_Champs-sur-Marne_001.jpg', 'Champs-sur-Marne', NULL, 'euro', 'journée', ARRAY['xviiie', 'jardins', 'élégant', 'cinéma'], 'http://www.chateau-champs-sur-marne.fr/'),
('Château de Vaux-le-Vicomte', 'Chef-d''œuvre de Le Vau, Le Brun et Le Nôtre, modèle de Versailles. Soirées aux chandelles l''été.', 'chateau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Vaux-le-vicomte_depuis_les_jardins.jpg/1280px-Vaux-le-vicomte_depuis_les_jardins.jpg', 'Maincy', NULL, 'euro2', 'journée', ARRAY['baroque', 'jardins', 'chandelles', 'fouquet'], 'https://vaux-le-vicomte.com/'),
('Château de Maisons-Laffitte', 'Chef-d''œuvre de l''architecture classique française par François Mansart, décors d''origine préservés.', 'chateau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Chateau_Maisons-Laffitte_001.JPG/1280px-Chateau_Maisons-Laffitte_001.JPG', 'Maisons-Laffitte', NULL, 'euro', 'journée', ARRAY['classique', 'mansart', 'architecture', 'chevaux'], 'http://www.chateau-maisons.fr/'),
('Château de Breteuil', 'Château familial avec mise en scène des contes de Perrault et magnifique jardin labellisé.', 'chateau', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Ch%C3%A2teau_de_Breteuil_-_facade.jpg/1280px-Ch%C3%A2teau_de_Breteuil_-_facade.jpg', 'Choisel', NULL, 'euro', 'journée', ARRAY['famille', 'contes', 'perrault', 'jardins'], 'https://www.breteuil.fr/');

-- MUSÉES
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website) VALUES
('Musée de l''Illusion', 'Expériences visuelles et sensorielles étonnantes, illusions d''optique et installations interactives.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Museum_of_Illusions_Zagreb.jpg/1280px-Museum_of_Illusions_Zagreb.jpg', 'Paris', '1', 'euro', '1h30', ARRAY['interactif', 'illusions', 'photos', 'famille'], 'https://museedelillusion.fr/'),
('Fondation Louis Vuitton', 'Bâtiment iconique de Frank Gehry abritant art moderne et contemporain avec vue panoramique.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Fondation_Louis_Vuitton%2C_Paris_16e%2C_North_view_20140927_1.jpg/1280px-Fondation_Louis_Vuitton%2C_Paris_16e%2C_North_view_20140927_1.jpg', 'Paris', '16', 'euro', '2h', ARRAY['architecture', 'art-moderne', 'gehry', 'vue'], 'https://www.fondationlouisvuitton.fr/'),
('Musée du Louvre', 'Le plus grand musée d''art au monde avec la Joconde, la Vénus de Milo et 35 000 œuvres exposées.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/1280px-Louvre_Museum_Wikimedia_Commons.jpg', 'Paris', '1', 'euro2', '2h30', ARRAY['art', 'joconde', 'incontournable', 'histoire'], 'https://www.louvre.fr/'),
('Musée d''Orsay', 'Ancienne gare reconvertie en musée impressionniste avec Monet, Van Gogh, Renoir et plus encore.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Mus%C3%A9e_d%27Orsay%2C_Paris_7e%2C_Northwest_view_20140402_1.jpg/1280px-Mus%C3%A9e_d%27Orsay%2C_Paris_7e%2C_Northwest_view_20140402_1.jpg', 'Paris', '7', 'euro', '1h30', ARRAY['impressionnisme', 'gare', 'art', 'xixe'], 'https://www.musee-orsay.fr/'),
('Musée de l''Orangerie', 'Écrin des Nymphéas de Monet et collection Walter-Guillaume d''art impressionniste et moderne.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Paris_-_Jardin_des_Tuileries_-_Mus%C3%A9e_de_l%27Orangerie_-_PA00085992_-_001.jpg/1280px-Paris_-_Jardin_des_Tuileries_-_Mus%C3%A9e_de_l%27Orangerie_-_PA00085992_-_001.jpg', 'Paris', '1', 'euro', '1h30', ARRAY['monet', 'nymphéas', 'impressionnisme', 'tuileries'], 'https://www.musee-orangerie.fr/'),
('Grand Palais', 'Monument emblématique de Paris avec sa verrière spectaculaire, accueillant grandes expositions.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Le_Grand_Palais_depuis_le_Petit_Palais%2C_Paris.jpg/1280px-Le_Grand_Palais_depuis_le_Petit_Palais%2C_Paris.jpg', 'Paris', '8', 'euro', '1h30', ARRAY['expositions', 'verrière', 'champs-élysées', 'architecture'], 'https://www.grandpalais.fr/'),
('Petit Palais', 'Musée des Beaux-Arts de la Ville de Paris avec collections permanentes gratuites et jardin intérieur.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Petit_Palais_-_2018-05-08.jpg/1280px-Petit_Palais_-_2018-05-08.jpg', 'Paris', '8', 'gratuit', '1h', ARRAY['gratuit', 'beaux-arts', 'jardin', 'classique'], 'https://www.petitpalais.paris.fr/'),
('Musée Grévin', 'Célèbre musée de cire avec plus de 200 personnalités en figures plus vraies que nature.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Grevin_Paris_entrance.jpg/800px-Grevin_Paris_entrance.jpg', 'Boulevard Montmartre', '9', 'euro2', '1h30', ARRAY['cire', 'célébrités', 'photos', 'famille'], 'https://www.grevin-paris.com/'),
('Musée des Arts et Métiers', 'Conservatoire des techniques et de l''innovation avec pendule de Foucault et avion de Blériot.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Avion3_-_Mus%C3%A9e_des_Arts_et_M%C3%A9tiers.jpg/1280px-Avion3_-_Mus%C3%A9e_des_Arts_et_M%C3%A9tiers.jpg', 'Paris', '3', 'euro', '3h', ARRAY['sciences', 'techniques', 'inventions', 'foucault'], 'https://www.arts-et-metiers.net/'),
('Musée de la Chasse et de la Nature', 'Collection unique sur les rapports homme-animal dans un hôtel particulier du Marais.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/P1040716_Paris_III_rue_des_Archives_mus%C3%A9e_de_la_Chasse_et_de_la_Nature_rwk.jpg/1024px-P1040716_Paris_III_rue_des_Archives_mus%C3%A9e_de_la_Chasse_et_de_la_Nature_rwk.jpg', 'Paris', '3', 'euro', '1h30', ARRAY['nature', 'animaux', 'marais', 'original'], 'https://www.chassenature.org/'),
('Musée Carnavalet', 'L''histoire de Paris des origines à nos jours dans deux hôtels particuliers du Marais.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Carnavalet_cour.jpg/1280px-Carnavalet_cour.jpg', 'Paris', '3', 'gratuit', '2h', ARRAY['paris', 'histoire', 'marais', 'gratuit'], 'https://www.carnavalet.paris.fr/'),
('Musée Picasso', 'La plus grande collection mondiale d''œuvres de Picasso dans l''Hôtel Salé au cœur du Marais.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Paris_Musee_Picasso_Facade.jpg/1024px-Paris_Musee_Picasso_Facade.jpg', 'Paris', '3', 'euro', '2h', ARRAY['picasso', 'art-moderne', 'marais', 'sculpture'], 'https://www.museepicassoparis.fr/'),
('Archives Nationales', 'Trésors de l''histoire de France dans le cadre somptueux de l''Hôtel de Soubise et Rohan.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/H%C3%B4tel_de_Soubise%2C_Paris_-_Courtyard_View.jpg/1280px-H%C3%B4tel_de_Soubise%2C_Paris_-_Courtyard_View.jpg', 'Paris', '3', 'gratuit', '1h30', ARRAY['histoire', 'archives', 'gratuit', 'documents'], 'https://www.archives-nationales.culture.gouv.fr/'),
('Musée de la Magie', 'Univers fascinant de la prestidigitation avec spectacles de magie et collection d''automates.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/P1010101_Paris_IV_Rue_Saint-Paul_mus%C3%A9e_de_la_magie_reducance.JPG/1280px-P1010101_Paris_IV_Rue_Saint-Paul_mus%C3%A9e_de_la_magie_reducance.JPG', 'Paris', '4', 'euro', '1h', ARRAY['magie', 'spectacle', 'enfants', 'insolite'], 'https://www.museedelamagie.com/'),
('Musée Curie', 'Musée dédié à Marie Curie et à l''histoire de la radioactivité dans son ancien laboratoire.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Institut_Curie_-_bureau_et_laboratoire_de_Marie_Curie.jpg/1280px-Institut_Curie_-_bureau_et_laboratoire_de_Marie_Curie.jpg', 'Paris', '5', 'gratuit', '50 minutes', ARRAY['sciences', 'gratuit', 'curie', 'radioactivité'], 'https://musee.curie.fr/'),
('Monnaie de Paris', 'Plus ancienne institution de France avec expositions sur l''art monétaire et ateliers créatifs.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Monnaie_de_Paris%2C_view_from_pont_des_Arts.jpg/1280px-Monnaie_de_Paris%2C_view_from_pont_des_Arts.jpg', 'Paris', '6', 'euro', '1h30', ARRAY['monnaie', 'histoire', 'seine', 'ateliers'], 'https://www.monnaiedeparis.fr/'),
('Musée de la Vie Romantique', 'Maison-atelier de style romantique évoquant George Sand et la vie artistique du XIXe siècle.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Mus%C3%A9e_de_la_Vie_romantique_-_cour.jpg/1024px-Mus%C3%A9e_de_la_Vie_romantique_-_cour.jpg', 'Paris', '9', 'euro', '1h30', ARRAY['romantisme', 'george-sand', 'xixe', 'jardin'], 'https://www.museevieromantique.paris.fr/'),
('Musée des Arts Forains', 'Collection unique de manèges et attractions de fête foraine anciens, sur réservation.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Pavillons-de-Bercy.jpg/1280px-Pavillons-de-Bercy.jpg', 'Paris', '12', 'euro', '2h', ARRAY['forain', 'manèges', 'vintage', 'insolite'], 'https://arts-forains.com/'),
('Musée Vivant du Fromage', 'Exploration interactive de l''univers fromager avec caves d''affinage et dégustations.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Fromages_01.jpg/1280px-Fromages_01.jpg', 'Paris', '4', 'euro', '2h30', ARRAY['fromage', 'gastronomie', 'dégustation', 'artisanat'], 'https://www.museedufromage.paris/'),
('Égouts de Paris', 'Visite souterraine du réseau d''assainissement parisien, témoignage unique du génie civil.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Paris_sewers_tours_dsc08022.jpg/1280px-Paris_sewers_tours_dsc08022.jpg', 'Paris', '7', 'euro', '1h', ARRAY['souterrain', 'insolite', 'ingénierie', 'histoire'], 'https://www.paris.fr/'),
('Palais Galliera', 'Musée de la Mode de la Ville de Paris avec expositions temporaires de haute couture.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Palais_Galliera_Paris_2012.jpg/1280px-Palais_Galliera_Paris_2012.jpg', 'Paris', '16', 'euro', '2h10', ARRAY['mode', 'couture', 'expositions', 'élégance'], 'https://www.palaisgalliera.paris.fr/'),
('Musée de Cluny', 'Musée national du Moyen Âge avec la Dame à la Licorne et thermes gallo-romains.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Mus%C3%A9e_de_Cluny_-_Les_thermes_de_Cluny.jpg/1280px-Mus%C3%A9e_de_Cluny_-_Les_thermes_de_Cluny.jpg', 'Paris', '5', 'euro', '1h30', ARRAY['moyen-âge', 'licorne', 'thermes', 'tapisseries'], 'https://www.musee-moyenage.fr/'),
('Institut du Monde Arabe', 'Architecture innovante de Jean Nouvel célébrant la culture arabo-musulmane.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Institut_du_Monde_Arabe%2C_Paris_5e%2C_France_002.JPG/1280px-Institut_du_Monde_Arabe%2C_Paris_5e%2C_France_002.JPG', 'Paris', '5', 'euro', '1h', ARRAY['architecture', 'culture-arabe', 'nouvel', 'vue'], 'https://www.imarabe.org/'),
('Grande Galerie de l''Évolution', 'Spectaculaire mise en scène de la biodiversité dans le Muséum national d''Histoire naturelle.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Grande_galerie_de_l%27Evolution.jpg/1280px-Grande_galerie_de_l%27Evolution.jpg', 'Paris', '5', 'euro', '2h15', ARRAY['nature', 'animaux', 'sciences', 'famille'], 'https://www.mnhn.fr/'),
('Musée Nissim de Camondo', 'Hôtel particulier Belle Époque avec collection d''arts décoratifs du XVIIIe siècle.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Mus%C3%A9e_Nissim_de_Camondo%2C_view_from_Parc_Monceau.jpg/1280px-Mus%C3%A9e_Nissim_de_Camondo%2C_view_from_Parc_Monceau.jpg', 'Paris', '8', 'euro', '1h30', ARRAY['décoratifs', 'xviiie', 'monceau', 'élégance'], 'https://madparis.fr/'),
('Musée Cognacq-Jay', 'Collection XVIIIe siècle des fondateurs de la Samaritaine dans un hôtel du Marais.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Musee_Cognacq_Jay_-_garden.jpg/1024px-Musee_Cognacq_Jay_-_garden.jpg', 'Paris', '3', 'euro', '45 minutes', ARRAY['xviiie', 'marais', 'peinture', 'décoratifs'], 'https://www.museecognacqjay.paris.fr/'),
('Musée Marmottan Monet', 'Plus grande collection mondiale d''œuvres de Claude Monet dans un hôtel particulier.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Musee_marmottan_monet.JPG/1024px-Musee_marmottan_monet.JPG', 'Paris', '16', 'euro', '45 minutes', ARRAY['monet', 'impressionnisme', 'nymphéas', 'intime'], 'https://www.marmottan.fr/'),
('Musée Cernuschi', 'Art asiatique dans un hôtel particulier avec jardin japonais près du Parc Monceau.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Mus%C3%A9e_Cernuschi%2C_fa%C3%A7ade.jpg/1024px-Mus%C3%A9e_Cernuschi%2C_fa%C3%A7ade.jpg', 'Paris', '8', 'euro', '1h30', ARRAY['asie', 'japon', 'chine', 'monceau'], 'https://www.cernuschi.paris.fr/'),
('Musée de Montmartre', 'Histoire du quartier bohème dans les ateliers où vécut Renoir, avec jardins du Renoir.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Musee_de_Montmartre_%28Paris%29_-_c%C3%B4t%C3%A9_jardin.jpg/1280px-Musee_de_Montmartre_%28Paris%29_-_c%C3%B4t%C3%A9_jardin.jpg', 'Paris', '18', 'euro', '2h', ARRAY['montmartre', 'bohème', 'renoir', 'jardins'], 'https://museedemontmartre.fr/'),
('Palais de Tokyo', 'Centre d''art contemporain le plus grand d''Europe, ouvert jusqu''à minuit.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Palais_de_Tokyo_seen_from_the_Seine.jpg/1280px-Palais_de_Tokyo_seen_from_the_Seine.jpg', 'Paris', '16', 'euro', '2h', ARRAY['contemporain', 'nocturne', 'expositions', 'avant-garde'], 'https://www.palaisdetokyo.com/'),
('Musée d''Art Moderne de Paris', 'Collection majeure d''art des XXe et XXIe siècles dans l''aile est du Palais de Tokyo.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Mus%C3%A9e_d%27art_moderne_de_Paris.JPG/1280px-Mus%C3%A9e_d%27art_moderne_de_Paris.JPG', 'Paris', '16', 'euro', '1h30', ARRAY['art-moderne', 'xxe', 'peinture', 'sculpture'], 'https://www.mam.paris.fr/'),
('Musée des Arts Décoratifs', 'Du Moyen Âge au design contemporain dans les ailes du Louvre sur les arts appliqués.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Louvre_-_Mus%C3%A9e_des_Arts_d%C3%A9coratifs.jpg/1280px-Louvre_-_Mus%C3%A9e_des_Arts_d%C3%A9coratifs.jpg', 'Paris', '1', 'euro', '1h30', ARRAY['design', 'mobilier', 'mode', 'décoratifs'], 'https://madparis.fr/'),
('Musée Rodin', 'Œuvres du sculpteur dans son hôtel particulier avec jardin de sculptures remarquable.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Le_penseur_de_la_Porte_de_lEnfer_%28mus%C3%A9e_Rodin%29_%284528252054%29.jpg/1024px-Le_penseur_de_la_Porte_de_lEnfer_%28mus%C3%A9e_Rodin%29_%284528252054%29.jpg', 'Paris', '7', 'euro', '1h30', ARRAY['sculpture', 'rodin', 'jardin', 'penseur'], 'https://www.musee-rodin.fr/'),
('Musée National des Arts Asiatiques - Guimet', 'Plus grande collection d''art asiatique hors d''Asie, des civilisations antiques à nos jours.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Mus%C3%A9e_Guimet_cour_japonaise.jpg/1280px-Mus%C3%A9e_Guimet_cour_japonaise.jpg', 'Paris', '16', 'euro', '2h', ARRAY['asie', 'bouddha', 'extrême-orient', 'civilisations'], 'https://www.guimet.fr/'),
('Musée de l''Air et de l''Espace', 'Plus ancien musée aéronautique au monde au Bourget avec avions mythiques et Concorde.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Concorde_du_Mus%C3%A9e_de_l%27Air_et_de_l%27Espace%2C_Le_Bourget%2C_France.jpg/1280px-Concorde_du_Mus%C3%A9e_de_l%27Air_et_de_l%27Espace%2C_Le_Bourget%2C_France.jpg', 'Le Bourget', NULL, 'euro', '2h30', ARRAY['aviation', 'espace', 'concorde', 'sciences'], 'https://www.museeairespace.fr/'),
('Musée Jacquemart-André', 'Collection exceptionnelle de maîtres italiens dans un hôtel particulier Second Empire.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/P1050217_Paris_VIII_boulevard_Haussmann_mus%C3%A9e_Jacquemart-Andr%C3%A9_rwk.JPG/1280px-P1050217_Paris_VIII_boulevard_Haussmann_mus%C3%A9e_Jacquemart-Andr%C3%A9_rwk.JPG', 'Paris', '8', 'euro', '1h15', ARRAY['italien', 'haussmann', 'peinture', 'salon-de-thé'], 'https://www.musee-jacquemart-andre.com/'),
('Hôtel des Invalides', 'Chef-d''œuvre d''architecture classique abritant le tombeau de Napoléon et musées militaires.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Les_Invalides%2C_Paris%2C_France.jpg/1280px-Les_Invalides%2C_Paris%2C_France.jpg', 'Paris', '7', 'euro', '3h', ARRAY['napoléon', 'militaire', 'architecture', 'dôme'], 'https://www.musee-armee.fr/'),
('Musée Zadkine', 'Atelier-musée du sculpteur Ossip Zadkine dans un jardin paisible de Montparnasse.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Mus%C3%A9e_Zadkine%2C_Paris_6e%2C_France_001.JPG/1024px-Mus%C3%A9e_Zadkine%2C_Paris_6e%2C_France_001.JPG', 'Paris', '6', 'euro', '1h', ARRAY['sculpture', 'zadkine', 'atelier', 'jardin'], 'https://www.zadkine.paris.fr/'),
('Conciergerie', 'Palais médiéval devenu prison révolutionnaire où fut enfermée Marie-Antoinette.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/La_Conciergerie_de_nuit.jpg/1280px-La_Conciergerie_de_nuit.jpg', 'Paris', '1', 'euro', '1h', ARRAY['révolution', 'prison', 'médiéval', 'marie-antoinette'], 'http://www.paris-conciergerie.fr/'),
('Mémorial de la Shoah', 'Lieu de mémoire et musée consacré à l''histoire du génocide des Juifs pendant la Seconde Guerre mondiale.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Memorial_de_la_Shoah%2C_Mur_des_Noms%2C_Paris_4e_002.jpg/1280px-Memorial_de_la_Shoah%2C_Mur_des_Noms%2C_Paris_4e_002.jpg', 'Paris', '4', 'gratuit', '1h30', ARRAY['mémoire', 'shoah', 'histoire', 'wwii'], 'http://www.memorialdelashoah.org/'),
('Maison de Victor Hugo', 'Appartement de l''écrivain place des Vosges où il vécut 16 ans et écrivit Les Misérables.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/H%C3%B4tel_de_Rohan-Gu%C3%A9m%C3%A9n%C3%A9e_-_Maison_de_Victor_Hugo.jpg/1024px-H%C3%B4tel_de_Rohan-Gu%C3%A9m%C3%A9n%C3%A9e_-_Maison_de_Victor_Hugo.jpg', 'Paris', '4', 'gratuit', '1h', ARRAY['hugo', 'littérature', 'vosges', 'romantisme'], 'http://www.maisonsvictorhugo.paris.fr/'),
('Musée Maillol', 'Collection d''art moderne centrée sur le sculpteur Aristide Maillol avec expositions temporaires.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/59_rue_de_Grenelle.jpg/800px-59_rue_de_Grenelle.jpg', 'Paris', '7', 'euro', '2h', ARRAY['sculpture', 'maillol', 'art-moderne', 'expositions'], 'https://www.museemaillol.com/'),
('Musée du Parfum Fragonard', 'Découverte gratuite de l''art de la parfumerie française et de son histoire.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Musee_du_Parfum%2C_Paris%2C_August_2010.jpg/1280px-Musee_du_Parfum%2C_Paris%2C_August_2010.jpg', 'Paris', '9', 'gratuit', '1h30', ARRAY['parfum', 'gratuit', 'artisanat', 'senteurs'], 'https://musee-parfum-paris.fragonard.com/'),
('Musée national de la Marine', 'Histoire maritime française rénovée avec maquettes de navires, tableaux et instruments.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Paris_-_Palais_de_Chaillot_-_Mus%C3%A9e_de_la_Marine.jpg/1280px-Paris_-_Palais_de_Chaillot_-_Mus%C3%A9e_de_la_Marine.jpg', 'Paris', '16', 'euro', '1h30', ARRAY['marine', 'bateaux', 'histoire', 'océan'], 'https://www.musee-marine.fr/'),
('Cité de l''Architecture et du Patrimoine', 'Plus grand centre au monde dédié à l''architecture, dans le Palais de Chaillot.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/MAHJ-Mus%C3%A9e_Cit%C3%A9_architecture.jpg/1280px-MAHJ-Mus%C3%A9e_Cit%C3%A9_architecture.jpg', 'Paris', '16', 'euro', '2h', ARRAY['architecture', 'patrimoine', 'maquettes', 'urbanisme'], 'https://www.citedelarchitecture.fr/'),
('Musée de l''Homme', 'Évolution de l''humanité et diversité des cultures dans le Palais de Chaillot.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/P1250081_Paris_XVI_musee_Homme_rwk.jpg/1280px-P1250081_Paris_XVI_musee_Homme_rwk.jpg', 'Paris', '16', 'euro', '1h30', ARRAY['anthropologie', 'préhistoire', 'cultures', 'sciences'], 'https://www.museedelhomme.fr/'),
('Musée du Chocolat Choco-Story', 'Histoire du cacao et du chocolat avec démonstrations et dégustations incluses.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Chocolate_-_stoass.jpg/1280px-Chocolate_-_stoass.jpg', 'Paris', '10', 'euro', '1h30', ARRAY['chocolat', 'dégustation', 'gourmand', 'famille'], 'https://www.museeduchocolat.fr/'),
('Musée du Chocolat + Dégustation', 'Visite complète avec dégustation premium de chocolats artisanaux.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Chocolate_-_stoass.jpg/1280px-Chocolate_-_stoass.jpg', 'Paris', '10', 'euro2', '1h30', ARRAY['chocolat', 'dégustation', 'gourmand', 'atelier'], 'https://www.museeduchocolat.fr/'),
('Cité des Sciences et de l''Industrie', 'Plus grand musée des sciences d''Europe avec Géode, planétarium et expositions interactives.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Geode_at_night.jpg/1280px-Geode_at_night.jpg', 'Paris', '19', 'euro', '1h30', ARRAY['sciences', 'interactif', 'famille', 'géode'], 'https://www.cite-sciences.fr/'),
('Musée Bourdelle', 'Atelier-musée du sculpteur Antoine Bourdelle, élève de Rodin, avec jardin de sculptures.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Mus%C3%A9e_Bourdelle%2C_Paris_%28France%29.jpg/1024px-Mus%C3%A9e_Bourdelle%2C_Paris_%28France%29.jpg', 'Paris', '15', 'euro', '1h30', ARRAY['sculpture', 'bourdelle', 'atelier', 'montparnasse'], 'https://www.bourdelle.paris.fr/'),
('Muséum national d''Histoire naturelle', 'Institution scientifique tricentenaire avec galeries, serres et ménagerie au Jardin des Plantes.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Grande_galerie_de_l%27%C3%A9volution_-_vue_ext%C3%A9rieure.JPG/1280px-Grande_galerie_de_l%27%C3%A9volution_-_vue_ext%C3%A9rieure.JPG', 'Paris', '5', 'euro', '2h', ARRAY['nature', 'sciences', 'animaux', 'serres'], 'https://www.mnhn.fr/'),
('Espace Dalí', 'Collection surréaliste de Salvador Dalí avec sculptures et gravures au cœur de Montmartre.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Dal%C3%AD_Paris.jpg/1024px-Dal%C3%AD_Paris.jpg', 'Paris', '18', 'euro', '1h', ARRAY['dalí', 'surréalisme', 'montmartre', 'sculptures'], 'https://daliparis.com/'),
('Musée du quai Branly - Jacques Chirac', 'Arts et civilisations d''Afrique, Asie, Océanie et Amériques dans une architecture végétalisée.', 'musee', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Mus%C3%A9e_du_quai_Branly_September_2016.jpg/1280px-Mus%C3%A9e_du_quai_Branly_September_2016.jpg', 'Paris', '7', 'euro', '2h30', ARRAY['ethnologie', 'arts-premiers', 'nouvel', 'jardins'], 'https://www.quaibranly.fr/');

-- EXPOSITIONS
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website) VALUES
('Atelier des Lumières', 'Expériences immersives monumentales dans une ancienne fonderie, projections à 360°.', 'expo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Atelier_des_Lumi%C3%A8res_2018.jpg/1280px-Atelier_des_Lumi%C3%A8res_2018.jpg', 'Paris', '11', 'euro', '1h30', ARRAY['immersif', 'numérique', 'art', 'spectacle'], 'https://www.atelier-lumieres.com/'),
('Bourse de Commerce - Collection Pinault', 'Art contemporain dans un monument historique restauré par Tadao Ando.', 'expo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Bourse_de_commerce_de_Paris_2021.jpg/1280px-Bourse_de_commerce_de_Paris_2021.jpg', 'Paris', '1', 'euro', '1h30', ARRAY['contemporain', 'pinault', 'ando', 'architecture'], 'https://www.pinaultcollection.com/boursedecommerce'),
('Centre Pompidou', 'Architecture high-tech iconique abritant le MNAM, la plus grande collection d''art moderne d''Europe.', 'expo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Centre_Georges-Pompidou.jpg/1280px-Centre_Georges-Pompidou.jpg', 'Paris', '4', 'euro', '2h', ARRAY['art-moderne', 'architecture', 'piano-rogers', 'expositions'], 'https://www.centrepompidou.fr/');

-- SPECTACLES
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website) VALUES
('Moulin Rouge', 'Légendaire cabaret parisien depuis 1889 avec le célèbre French Cancan et revue Féerie.', 'spectacle', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Moulin_rouge_at_midnight.jpg/1024px-Moulin_rouge_at_midnight.jpg', 'Paris', '18', 'euro3', '1h40', ARRAY['cabaret', 'french-cancan', 'mythique', 'soirée'], 'https://www.moulinrouge.fr/'),
('Lido de Paris', 'Cabaret des Champs-Élysées avec spectacle et option dîner au Fouquet''s.', 'spectacle', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Paris_75008_Champs_Elys%C3%A9es_no_116_bis_Lido_at_night.jpg/1280px-Paris_75008_Champs_Elys%C3%A9es_no_116_bis_Lido_at_night.jpg', 'Paris', '8', 'euro2', '2h30', ARRAY['cabaret', 'champs-élysées', 'dîner', 'revue'], 'https://www.lido-paris.com/'),
('Folies Bergère', 'Salle de spectacles mythique accueillant concerts, one-man shows et comédies musicales.', 'spectacle', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Folies-berg%C3%A8re.jpg/1024px-Folies-berg%C3%A8re.jpg', 'Paris', '9', 'euro2', NULL, ARRAY['spectacle', 'variétés', 'mythique', 'concerts'], 'https://www.foliesbergere.com/');

-- QUARTIERS
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website) VALUES
('Quartier Châtelet', 'Cœur historique de Paris entre théâtres, fontaine de la Victoire et rues commerçantes.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Place_du_Ch%C3%A2telet%2C_Paris_4e.jpg/1280px-Place_du_Ch%C3%A2telet%2C_Paris_4e.jpg', 'Paris', '1', 'gratuit', NULL, ARRAY['centre', 'théâtres', 'shopping', 'histoire'], NULL),
('Montmartre', 'Village bohème avec le Sacré-Cœur, vignes, artistes de rue et cafés légendaires.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Montmartre_Sacre_Coeur_Paris.jpg/1280px-Montmartre_Sacre_Coeur_Paris.jpg', 'Paris', '18', 'gratuit', NULL, ARRAY['bohème', 'sacré-coeur', 'artistes', 'romantique'], NULL),
('Cimetière du Père-Lachaise', 'Plus grand cimetière de Paris avec tombes de célébrités dans un décor romantique.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/P%C3%A8re-Lachaise_-_Division_69_-_All%C3%A9e_transversale_n%C2%B01_01.jpg/1280px-P%C3%A8re-Lachaise_-_Division_69_-_All%C3%A9e_transversale_n%C2%B01_01.jpg', 'Paris', '20', 'gratuit', NULL, ARRAY['cimetière', 'célébrités', 'romantique', 'promenade'], 'https://pere-lachaise.com/'),
('Place Vendôme', 'Place octogonale prestigieuse avec colonne Vendôme et joailliers de luxe.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Place_Vend%C3%B4me%2C_Paris_1er%2C_Northwest_view_20140102_1.jpg/1280px-Place_Vend%C3%B4me%2C_Paris_1er%2C_Northwest_view_20140102_1.jpg', 'Paris', '1', 'gratuit', NULL, ARRAY['luxe', 'joaillerie', 'napoléon', 'élégance'], NULL),
('Le Marais', 'Quartier historique avec hôtels particuliers, musées, boutiques branchées et communauté LGBT.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Place_des_Vosges_Paris_Mai_2006_002.jpg/1280px-Place_des_Vosges_Paris_Mai_2006_002.jpg', 'Paris', '4', 'gratuit', NULL, ARRAY['historique', 'shopping', 'lgbt', 'vosges'], NULL),
('Champs-Élysées', 'La plus belle avenue du monde entre Arc de Triomphe et Place de la Concorde.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Avenue_des_Champs-%C3%89lys%C3%A9es_July_24%2C_2009_N1.jpg/1280px-Avenue_des_Champs-%C3%89lys%C3%A9es_July_24%2C_2009_N1.jpg', 'Paris', '8', 'gratuit', NULL, ARRAY['célèbre', 'shopping', 'arc-triomphe', 'promenade'], NULL),
('Île de la Cité', 'Berceau historique de Paris avec Notre-Dame, Sainte-Chapelle et Conciergerie.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/%C3%8Ele_de_la_Cit%C3%A9.jpg/1280px-%C3%8Ele_de_la_Cit%C3%A9.jpg', 'Île de la Cité', NULL, 'gratuit', NULL, ARRAY['histoire', 'notre-dame', 'origines', 'gothique'], NULL),
('Quartier Latin', 'Quartier étudiant historique avec universités, librairies, cinémas et vie nocturne.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Panth%C3%A9on_from_Luxembourg_Garden%2C_Paris_5e_20140223_1.jpg/1280px-Panth%C3%A9on_from_Luxembourg_Garden%2C_Paris_5e_20140223_1.jpg', 'Paris', '5', 'gratuit', NULL, ARRAY['étudiant', 'universités', 'librairies', 'animation'], NULL),
('Canal Saint-Martin', 'Canal romantique bordé de platanes avec écluses, passerelles et terrasses branchées.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Canal_Saint-Martin_-_passerelle_Alibert_-_04.jpg/1280px-Canal_Saint-Martin_-_passerelle_Alibert_-_04.jpg', 'Paris', '10', 'gratuit', NULL, ARRAY['romantique', 'canal', 'terrasses', 'branché'], NULL),
('Quartier Opéra', 'Quartier haussmannien autour du Palais Garnier avec grands magasins et passages couverts.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Palais_Garnier%27s_grand_fa%C3%A7ade%2C_2010.jpg/1280px-Palais_Garnier%27s_grand_fa%C3%A7ade%2C_2010.jpg', 'Paris', '9', 'gratuit', NULL, ARRAY['opéra', 'haussmann', 'shopping', 'passages'], NULL),
('Grands Boulevards', 'Artères animées avec théâtres, cinémas, passages couverts et architecture XIXe.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Passage_Jouffroy_Paris_France.jpg/1024px-Passage_Jouffroy_Paris_France.jpg', 'Paris', '2', 'gratuit', NULL, ARRAY['animation', 'théâtres', 'passages', 'xixe'], NULL),
('Quartier du Louvre', 'Autour du plus grand musée du monde, entre Palais Royal et Pont des Arts.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/1280px-Louvre_Museum_Wikimedia_Commons.jpg', 'Paris', '1', 'gratuit', NULL, ARRAY['louvre', 'culture', 'pyramide', 'seine'], NULL),
('Quartier Tour Eiffel / Trocadéro', 'Icône de Paris avec esplanades, fontaines et vue exceptionnelle sur la Dame de Fer.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg', 'Paris', '7', 'gratuit', NULL, ARRAY['tour-eiffel', 'iconique', 'vue', 'photo'], NULL),
('Bastille', 'Quartier populaire historique devenu branché avec vie nocturne, marché et opéra moderne.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/P1010310_Paris_IV_Place_de_la_Bastille_colonne_de_Juillet_reducance.JPG/1024px-P1010310_Paris_IV_Place_de_la_Bastille_colonne_de_Juillet_reducance.JPG', 'Paris', '4', 'gratuit', NULL, ARRAY['révolution', 'nocturne', 'branché', 'marché'], NULL),
('Quartier Asiatique', 'Le plus grand Chinatown d''Europe avec restaurants, commerces et culture asiatique.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Paris_13e_-_Quartier_asiatique.jpg/1280px-Paris_13e_-_Quartier_asiatique.jpg', 'Paris', '13', 'gratuit', NULL, ARRAY['asiatique', 'gastronomie', 'chinatown', 'authentique'], NULL),
('Promenade Louvre - Champs-Élysées', 'Balade mythique traversant Tuileries, Concorde et remontant la plus belle avenue du monde.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Luxor_Obelisk_and_Arc_de_Triomphe_-_Paris%2C_France_-_April_20%2C_2011.jpg/1280px-Luxor_Obelisk_and_Arc_de_Triomphe_-_Paris%2C_France_-_April_20%2C_2011.jpg', 'Paris', '1', 'gratuit', '45 minutes', ARRAY['promenade', 'iconique', 'tuileries', 'concorde'], NULL),
('Esplanade du Trocadéro', 'Point de vue emblématique sur la Tour Eiffel avec jardins et fontaines monumentales.', 'quartier', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Eiffel_Tower_from_the_Trocadero.jpg/1280px-Eiffel_Tower_from_the_Trocadero.jpg', 'Paris', '16', 'gratuit', '30 minutes', ARRAY['vue', 'tour-eiffel', 'fontaines', 'photo'], NULL);

-- TOURISME HISTORIQUE
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website) VALUES
('Sacré-Cœur (Basilique)', 'Basilique romano-byzantine dominant Paris depuis la butte Montmartre, accès gratuit.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Le_sacre_coeur.jpg/1024px-Le_sacre_coeur.jpg', 'Paris', '18', 'gratuit', '1h', ARRAY['basilique', 'montmartre', 'vue', 'religieux'], 'https://www.sacre-coeur-montmartre.com/'),
('Sacré-Cœur (Dôme)', 'Montée au dôme pour une vue panoramique exceptionnelle sur Paris à 360°.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Le_sacre_coeur.jpg/1024px-Le_sacre_coeur.jpg', 'Paris', '18', 'euro', '1h30', ARRAY['panorama', 'montmartre', 'vue', 'dôme'], 'https://www.sacre-coeur-montmartre.com/'),
('Invalides (Extérieurs)', 'Promenade gratuite autour du monument et de son esplanade avec vue sur le dôme doré.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Les_Invalides%2C_Paris%2C_France.jpg/1280px-Les_Invalides%2C_Paris%2C_France.jpg', 'Paris', '7', 'gratuit', '1h', ARRAY['napoléon', 'dôme', 'militaire', 'promenade'], 'https://www.musee-armee.fr/'),
('Tour Eiffel (Sans montée)', 'Admirer la Dame de Fer depuis le Champ de Mars et le Trocadéro, gratuitement.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg', 'Tour Eiffel', '7', 'gratuit', '30 minutes', ARRAY['tour-eiffel', 'iconique', 'photo', 'gratuit'], 'https://www.toureiffel.paris/'),
('Tour Eiffel 2ème étage (Ascenseur)', 'Montée en ascenseur jusqu''au 2ème étage avec vue spectaculaire sur Paris.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg', 'Tour Eiffel', '7', 'euro2', '1h30', ARRAY['tour-eiffel', 'vue', 'ascenseur', 'incontournable'], 'https://www.toureiffel.paris/'),
('Tour Eiffel 2ème étage (Escalier)', 'Montée sportive à pied pour une expérience unique avec accès aux piliers historiques.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg', 'Tour Eiffel', '7', 'euro', '2h', ARRAY['tour-eiffel', 'sport', 'escalier', 'économique'], 'https://www.toureiffel.paris/'),
('Conciergerie', 'Prison révolutionnaire dans le Palais de la Cité, dernière demeure de Marie-Antoinette.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/La_Conciergerie_de_nuit.jpg/1280px-La_Conciergerie_de_nuit.jpg', 'Paris', '1', 'euro', '1h', ARRAY['révolution', 'prison', 'médiéval', 'histoire'], 'http://www.paris-conciergerie.fr/'),
('Panthéon (Extérieurs)', 'Admirez le monument néoclassique abritant les grands Hommes depuis la place du Panthéon.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Pantheon_of_Paris_007.JPG/1280px-Pantheon_of_Paris_007.JPG', 'Panthéon', '5', 'gratuit', '30 minutes', ARRAY['néoclassique', 'grands-hommes', 'quartier-latin', 'architecture'], 'http://www.paris-pantheon.fr/'),
('Panthéon (Visite)', 'Visite du monument avec crypte des personnalités illustres et pendule de Foucault.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Pantheon_of_Paris_007.JPG/1280px-Pantheon_of_Paris_007.JPG', 'Panthéon', '5', 'euro', '2h', ARRAY['crypte', 'foucault', 'histoire', 'grands-hommes'], 'http://www.paris-pantheon.fr/'),
('Assemblée Nationale', 'Visite gratuite du Palais Bourbon, siège de la démocratie française depuis 1798.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Assembl%C3%A9e_Nationale_%28Paris%29.JPG/1280px-Assembl%C3%A9e_Nationale_%28Paris%29.JPG', 'Paris', '7', 'gratuit', '1h30', ARRAY['politique', 'démocratie', 'palais-bourbon', 'gratuit'], 'https://www.assemblee-nationale.fr/'),
('Opéra Garnier (Sans guide)', 'Visite libre du chef-d''œuvre de Charles Garnier avec grand escalier et plafond Chagall.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Palais_Garnier%27s_grand_fa%C3%A7ade%2C_2010.jpg/1280px-Palais_Garnier%27s_grand_fa%C3%A7ade%2C_2010.jpg', 'Paris', '9', 'euro', '1h30', ARRAY['opéra', 'garnier', 'chagall', 'architecture'], 'https://www.operadeparis.fr/'),
('Opéra Garnier (Avec guide)', 'Visite guidée approfondie révélant les secrets et l''histoire du Palais Garnier.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Palais_Garnier%27s_grand_fa%C3%A7ade%2C_2010.jpg/1280px-Palais_Garnier%27s_grand_fa%C3%A7ade%2C_2010.jpg', 'Paris', '9', 'euro2', '1h30', ARRAY['opéra', 'garnier', 'guidée', 'secrets'], 'https://www.operadeparis.fr/'),
('Arc de Triomphe (Extérieurs)', 'Admirer le monument napoléonien et la flamme du Soldat inconnu gratuitement.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg/1024px-Arc_de_Triomphe%2C_Paris_21_October_2010.jpg', 'Paris', '8', 'gratuit', '30 minutes', ARRAY['napoléon', 'étoile', 'champs-élysées', 'monument'], NULL),
('Arc de Triomphe (Visite)', 'Montée sur la terrasse panoramique offrant une vue à 360° sur Paris et ses avenues.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg/1024px-Arc_de_Triomphe%2C_Paris_21_October_2010.jpg', 'Paris', '8', 'euro2', '1h', ARRAY['panorama', 'napoléon', 'vue', 'champs-élysées'], 'http://www.paris-arc-de-triomphe.fr/'),
('Sainte-Chapelle', 'Joyau gothique rayonnant avec vitraux du XIIIe siècle exceptionnels.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Sainte_Chapelle_-_Upper_Chapel.jpg/800px-Sainte_Chapelle_-_Upper_Chapel.jpg', 'Paris', '1', 'euro', '1h', ARRAY['gothique', 'vitraux', 'île-de-la-cité', 'chef-d-oeuvre'], 'http://www.sainte-chapelle.fr/'),
('Notre-Dame (Sans montée)', 'Visite gratuite de la cathédrale restaurée après l''incendie de 2019.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Notre-Dame_de_Paris%2C_4_October_2017.jpg/1024px-Notre-Dame_de_Paris%2C_4_October_2017.jpg', 'Île de la Cité', '4', 'gratuit', '1h', ARRAY['cathédrale', 'gothique', 'gratuit', 'histoire'], 'https://www.notredamedeparis.fr/'),
('Notre-Dame (Avec montée tours)', 'Ascension des tours pour voir les gargouilles et la vue sur Paris.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Notre-Dame_de_Paris%2C_4_October_2017.jpg/1024px-Notre-Dame_de_Paris%2C_4_October_2017.jpg', 'Île de la Cité', '4', 'euro', '2h', ARRAY['cathédrale', 'tours', 'gargouilles', 'panorama'], 'https://www.notredamedeparis.fr/'),
('Tour Montparnasse', 'Vue panoramique à 210m de haut, la meilleure vue sur Paris avec la Tour Eiffel.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Tour_Montparnasse_from_the_Tour_Eiffel%2C_4_July_2009.jpg/800px-Tour_Montparnasse_from_the_Tour_Eiffel%2C_4_July_2009.jpg', 'Quartier Montparnasse', '15', 'euro2', '1h', ARRAY['panorama', 'vue', 'moderne', 'terrasse'], 'https://www.tourmontparnasse56.com/'),
('BnF Richelieu', 'Bibliothèque historique avec salle de lecture ovale magnifique et expositions.', 'tourisme_historique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/BnF_Richelieu_-_salle_ovale_2.jpg/1280px-BnF_Richelieu_-_salle_ovale_2.jpg', 'Paris', '2', 'euro', '1h30', ARRAY['bibliothèque', 'architecture', 'culture', 'livres'], 'https://www.bnf.fr/');

-- AUTRES
INSERT INTO activities (name, description, category, image_url, location, arrondissement, price_range, duration, tags, website) VALUES
('Bus Touristique', 'Découverte de Paris en bus à impériale avec commentaires et arrêts multiples.', 'autre', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Open_Tour_Paris.jpg/1280px-Open_Tour_Paris.jpg', 'Paris', NULL, 'euro2', '1h30', ARRAY['bus', 'tour', 'commentaires', 'pratique'], 'https://www.bigbustours.com/'),
('E-Motion', 'Expériences de réalité virtuelle et simulateurs de sensations fortes.', 'autre', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Virtual_Reality_Gaming.jpg/1280px-Virtual_Reality_Gaming.jpg', 'Paris', '2', 'euro2', '15-30 minutes', ARRAY['vr', 'simulateur', 'sensations', 'technologie'], NULL),
('Catacombes de Paris', 'Ossuaire souterrain contenant les restes de 6 millions de Parisiens.', 'autre', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Paris_Catacombes_BW_1.jpg/1024px-Paris_Catacombes_BW_1.jpg', 'Paris', '14', 'euro', '1h30', ARRAY['souterrain', 'ossuaire', 'insolite', 'histoire'], 'https://www.catacombes.paris.fr/'),
('Galeries Lafayette Haussmann', 'Grand magasin emblématique avec coupole Art Nouveau et terrasse panoramique gratuite.', 'autre', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Galeries_Lafayette_coupole.jpg/1024px-Galeries_Lafayette_coupole.jpg', 'Paris', '9', 'gratuit', NULL, ARRAY['shopping', 'coupole', 'gratuit', 'vue'], 'https://www.galerieslafayette.com/');